local mod = get_mod("PlasmaBFG")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "group_primary_fire",
				type = "group",
				title = "group_primary_fire",
				sub_widgets = {
					{
						setting_id = "hipfire_release_factor",
						title = "hipfire_release_factor",
						type = "numeric",
						tooltip = "hipfire_release_factor_description",
						default_value = 1.00,
						range = { 0.70, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_shot_total_time",
						title = "primary_shot_total_time",
						type = "numeric",
						tooltip = "primary_shot_total_time_description",
						default_value = 0.50,
						range = { 0.25, 0.80 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_rechain_time",
						title = "primary_rechain_time",
						type = "numeric",
						tooltip = "primary_rechain_time_description",
						default_value = 0.45,
						range = { 0.10, 0.80 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_sprint_ready_up_time",
						title = "primary_sprint_ready_up_time",
						type = "numeric",
						tooltip = "primary_sprint_ready_up_time_description",
						default_value = 0.60,
						range = { 0.00, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_charge_sprint_ready_up_time",
						title = "primary_charge_sprint_ready_up_time",
						type = "numeric",
						tooltip = "primary_charge_sprint_ready_up_time_description",
						default_value = 0.40,
						range = { 0.00, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "held_primary_assist_enabled",
						title = "held_primary_assist_enabled",
						type = "checkbox",
						tooltip = "held_primary_assist_enabled_description",
						default_value = true,
					},
					{
						setting_id = "recoil_multiplier",
						title = "recoil_multiplier",
						type = "numeric",
						tooltip = "recoil_multiplier_description",
						default_value = 1.00,
						range = { 0.05, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "spread_multiplier",
						title = "spread_multiplier",
						type = "numeric",
						tooltip = "spread_multiplier_description",
						default_value = 1.00,
						range = { 0.05, 1.00 },
						decimals_number = 2,
					},
				},
			},
			{
				setting_id = "group_ammo",
				type = "group",
				title = "group_ammo",
				sub_widgets = {
					{
						setting_id = "primary_ammo_cost",
						title = "primary_ammo_cost",
						type = "numeric",
						tooltip = "primary_ammo_cost_description",
						default_value = 3,
						range = { 1, 3 },
						decimals_number = 0,
					},
					{
						setting_id = "charged_ammo_max",
						title = "charged_ammo_max",
						type = "numeric",
						tooltip = "charged_ammo_max_description",
						default_value = 8,
						range = { 1, 8 },
						decimals_number = 0,
					},
					{
						setting_id = "ammo_pool_multiplier",
						title = "ammo_pool_multiplier",
						type = "numeric",
						tooltip = "ammo_pool_multiplier_description",
						default_value = 1.00,
						range = { 1.00, 4.00 },
						decimals_number = 2,
					},
					{
						setting_id = "auto_reload_empty_enabled",
						title = "auto_reload_empty_enabled",
						type = "checkbox",
						tooltip = "auto_reload_empty_enabled_description",
						default_value = true,
					},
				},
			},
			{
				setting_id = "group_heat",
				type = "group",
				title = "group_heat",
				sub_widgets = {
					{
						setting_id = "auto_vent_enabled",
						title = "auto_vent_enabled",
						type = "checkbox",
						tooltip = "auto_vent_enabled_description",
						default_value = true,
					},
					{
						setting_id = "auto_vent_start_percent",
						title = "auto_vent_start_percent",
						type = "numeric",
						tooltip = "auto_vent_start_percent_description",
						default_value = 99,
						range = { 80, 99 },
						decimals_number = 0,
					},
					{
						setting_id = "disable_overheat_explosion",
						title = "disable_overheat_explosion",
						type = "checkbox",
						tooltip = "disable_overheat_explosion_description",
						default_value = true,
					},
					{
						setting_id = "vent_damage_multiplier",
						title = "vent_damage_multiplier",
						type = "numeric",
						tooltip = "vent_damage_multiplier_description",
						default_value = 1.00,
						range = { 0.00, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "vent_speed_multiplier",
						title = "vent_speed_multiplier",
						type = "numeric",
						tooltip = "vent_speed_multiplier_description",
						default_value = 1.00,
						range = { 0.25, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_charge_duration_basic",
						title = "primary_charge_duration_basic",
						type = "numeric",
						tooltip = "primary_charge_duration_basic_description",
						default_value = 1.00,
						range = { 0.20, 1.50 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_charge_duration_perfect",
						title = "primary_charge_duration_perfect",
						type = "numeric",
						tooltip = "primary_charge_duration_perfect_description",
						default_value = 0.50,
						range = { 0.10, 1.00 },
						decimals_number = 2,
					},
					{
						setting_id = "primary_charge_overheat_basic",
						title = "primary_charge_overheat_basic",
						type = "numeric",
						tooltip = "primary_charge_overheat_basic_description",
						default_value = 0.090,
						range = { 0.000, 0.200 },
						decimals_number = 3,
					},
					{
						setting_id = "primary_charge_overheat_perfect",
						title = "primary_charge_overheat_perfect",
						type = "numeric",
						tooltip = "primary_charge_overheat_perfect_description",
						default_value = 0.045,
						range = { 0.000, 0.100 },
						decimals_number = 3,
					},
					{
						setting_id = "primary_charge_full_overheat",
						title = "primary_charge_full_overheat",
						type = "numeric",
						tooltip = "primary_charge_full_overheat_description",
						default_value = 0.025,
						range = { 0.000, 0.100 },
						decimals_number = 3,
					},
					{
						setting_id = "primary_shot_overheat_basic",
						title = "primary_shot_overheat_basic",
						type = "numeric",
						tooltip = "primary_shot_overheat_basic_description",
						default_value = 0.300,
						range = { 0.000, 0.400 },
						decimals_number = 3,
					},
					{
						setting_id = "primary_shot_overheat_perfect",
						title = "primary_shot_overheat_perfect",
						type = "numeric",
						tooltip = "primary_shot_overheat_perfect_description",
						default_value = 0.150,
						range = { 0.000, 0.250 },
						decimals_number = 3,
					},
				},
			},
			{
				setting_id = "group_damage",
				type = "group",
				title = "group_damage",
				sub_widgets = {
					{
						setting_id = "primary_bfg_impact",
						title = "primary_bfg_impact",
						type = "checkbox",
						tooltip = "primary_bfg_impact_description",
						default_value = true,
					},
					{
						setting_id = "primary_demolition_explosion",
						title = "primary_demolition_explosion",
						type = "checkbox",
						tooltip = "primary_demolition_explosion_description",
						default_value = true,
					},
					{
						setting_id = "primary_penetration_depth",
						title = "primary_penetration_depth",
						type = "numeric",
						tooltip = "primary_penetration_depth_description",
						default_value = 1.25,
						range = { 1.25, 6.00 },
						decimals_number = 2,
					},
					{
						setting_id = "charged_penetration_depth",
						title = "charged_penetration_depth",
						type = "numeric",
						tooltip = "charged_penetration_depth_description",
						default_value = 2.00,
						range = { 2.00, 8.00 },
						decimals_number = 2,
					},
					{
						setting_id = "penetration_target_count",
						title = "penetration_target_count",
						type = "numeric",
						tooltip = "penetration_target_count_description",
						default_value = 2,
						range = { 2, 12 },
						decimals_number = 0,
					},
					{
						setting_id = "charged_explosion_radius_multiplier",
						title = "charged_explosion_radius_multiplier",
						type = "numeric",
						tooltip = "charged_explosion_radius_multiplier_description",
						default_value = 1.00,
						range = { 1.00, 2.50 },
						decimals_number = 2,
					},
				},
			},
		},
	},
}
