local mod = get_mod("RequisitionAuspex")

return {
    name = "Curios Auspex",
    description = mod:localize("mod_description"),
    is_togglable = true,
    options = {
        widgets = {
            {
                setting_id = "group_stores",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "scan_armoury",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "scan_melk",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "store_refresh_notifications",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "hub_widget_enabled",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "hub_widget_custom_hud",
                        type = "checkbox",
                        default_value = true,
                    },
                    {
                        setting_id = "hub_widget_scale",
                        type = "dropdown",
                        default_value = 100,
                        options = {
                            { text = "widget_scale_50", value = 50 },
                            { text = "widget_scale_60", value = 60 },
                            { text = "widget_scale_70", value = 70 },
                            { text = "widget_scale_80", value = 80 },
                            { text = "widget_scale_90", value = 90 },
                            { text = "widget_scale_100", value = 100 },
                            { text = "widget_scale_110", value = 110 },
                            { text = "widget_scale_120", value = 120 },
                            { text = "widget_scale_130", value = 130 },
                            { text = "widget_scale_140", value = 140 },
                            { text = "widget_scale_150", value = 150 },
                        },
                    },
                    {
                        setting_id = "hub_widget_x",
                        type = "numeric",
                        default_value = 82,
                        range = { 0, 100 },
                        decimals_number = 0,
                    },
                    {
                        setting_id = "hub_widget_y",
                        type = "numeric",
                        default_value = 12,
                        range = { 0, 100 },
                        decimals_number = 0,
                    },
                },
            },
            {
                setting_id = "group_curio_wishlist",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "minimum_toughness",
                        type = "dropdown",
                        default_value = 17,
                        options = {
                            { text = "roll_5_percent", value = 5 },
                            { text = "roll_6_percent", value = 6 },
                            { text = "roll_7_percent", value = 7 },
                            { text = "roll_8_percent", value = 8 },
                            { text = "roll_9_percent", value = 9 },
                            { text = "roll_10_percent", value = 10 },
                            { text = "roll_11_percent", value = 11 },
                            { text = "roll_12_percent", value = 12 },
                            { text = "roll_13_percent", value = 13 },
                            { text = "roll_14_percent", value = 14 },
                            { text = "roll_15_percent", value = 15 },
                            { text = "roll_16_percent", value = 16 },
                            { text = "roll_17_percent", value = 17 },
                        },
                    },
                    {
                        setting_id = "target_toughness",
                        type = "dropdown",
                        default_value = 3,
                        options = {
                            { text = "quantity_0", value = 0 },
                            { text = "quantity_1", value = 1 },
                            { text = "quantity_2", value = 2 },
                            { text = "quantity_3", value = 3 },
                            { text = "quantity_4", value = 4 },
                            { text = "quantity_5", value = 5 },
                            { text = "quantity_6", value = 6 },
                            { text = "quantity_7", value = 7 },
                            { text = "quantity_8", value = 8 },
                            { text = "quantity_9", value = 9 },
                            { text = "quantity_10", value = 10 },
                            { text = "quantity_11", value = 11 },
                            { text = "quantity_12", value = 12 },
                            { text = "quantity_13", value = 13 },
                            { text = "quantity_14", value = 14 },
                            { text = "quantity_15", value = 15 },
                            { text = "quantity_16", value = 16 },
                            { text = "quantity_17", value = 17 },
                            { text = "quantity_18", value = 18 },
                            { text = "quantity_19", value = 19 },
                            { text = "quantity_20", value = 20 },
                        },
                    },
                    {
                        setting_id = "minimum_health",
                        type = "dropdown",
                        default_value = 21,
                        options = {
                            { text = "roll_5_percent", value = 5 },
                            { text = "roll_6_percent", value = 6 },
                            { text = "roll_7_percent", value = 7 },
                            { text = "roll_8_percent", value = 8 },
                            { text = "roll_9_percent", value = 9 },
                            { text = "roll_10_percent", value = 10 },
                            { text = "roll_11_percent", value = 11 },
                            { text = "roll_12_percent", value = 12 },
                            { text = "roll_13_percent", value = 13 },
                            { text = "roll_14_percent", value = 14 },
                            { text = "roll_15_percent", value = 15 },
                            { text = "roll_16_percent", value = 16 },
                            { text = "roll_17_percent", value = 17 },
                            { text = "roll_18_percent", value = 18 },
                            { text = "roll_19_percent", value = 19 },
                            { text = "roll_20_percent", value = 20 },
                            { text = "roll_21_percent", value = 21 },
                        },
                    },
                    {
                        setting_id = "target_health",
                        type = "dropdown",
                        default_value = 3,
                        options = {
                            { text = "quantity_0", value = 0 },
                            { text = "quantity_1", value = 1 },
                            { text = "quantity_2", value = 2 },
                            { text = "quantity_3", value = 3 },
                            { text = "quantity_4", value = 4 },
                            { text = "quantity_5", value = 5 },
                            { text = "quantity_6", value = 6 },
                            { text = "quantity_7", value = 7 },
                            { text = "quantity_8", value = 8 },
                            { text = "quantity_9", value = 9 },
                            { text = "quantity_10", value = 10 },
                            { text = "quantity_11", value = 11 },
                            { text = "quantity_12", value = 12 },
                            { text = "quantity_13", value = 13 },
                            { text = "quantity_14", value = 14 },
                            { text = "quantity_15", value = 15 },
                            { text = "quantity_16", value = 16 },
                            { text = "quantity_17", value = 17 },
                            { text = "quantity_18", value = 18 },
                            { text = "quantity_19", value = 19 },
                            { text = "quantity_20", value = 20 },
                        },
                    },
                    {
                        setting_id = "minimum_stamina",
                        type = "dropdown",
                        default_value = 3,
                        options = {
                            { text = "roll_plus_1", value = 1 },
                            { text = "roll_plus_2", value = 2 },
                            { text = "roll_plus_3", value = 3 },
                        },
                    },
                    {
                        setting_id = "target_stamina",
                        type = "dropdown",
                        default_value = 3,
                        options = {
                            { text = "quantity_0", value = 0 },
                            { text = "quantity_1", value = 1 },
                            { text = "quantity_2", value = 2 },
                            { text = "quantity_3", value = 3 },
                            { text = "quantity_4", value = 4 },
                            { text = "quantity_5", value = 5 },
                            { text = "quantity_6", value = 6 },
                            { text = "quantity_7", value = 7 },
                            { text = "quantity_8", value = 8 },
                            { text = "quantity_9", value = 9 },
                            { text = "quantity_10", value = 10 },
                            { text = "quantity_11", value = 11 },
                            { text = "quantity_12", value = 12 },
                            { text = "quantity_13", value = 13 },
                            { text = "quantity_14", value = 14 },
                            { text = "quantity_15", value = 15 },
                            { text = "quantity_16", value = 16 },
                            { text = "quantity_17", value = 17 },
                            { text = "quantity_18", value = 18 },
                            { text = "quantity_19", value = 19 },
                            { text = "quantity_20", value = 20 },
                        },
                    },
                    {
                        setting_id = "target_wounds",
                        type = "dropdown",
                        default_value = 0,
                        options = {
                            { text = "quantity_0", value = 0 },
                            { text = "quantity_1", value = 1 },
                            { text = "quantity_2", value = 2 },
                            { text = "quantity_3", value = 3 },
                            { text = "quantity_4", value = 4 },
                            { text = "quantity_5", value = 5 },
                            { text = "quantity_6", value = 6 },
                            { text = "quantity_7", value = 7 },
                            { text = "quantity_8", value = 8 },
                            { text = "quantity_9", value = 9 },
                            { text = "quantity_10", value = 10 },
                            { text = "quantity_11", value = 11 },
                            { text = "quantity_12", value = 12 },
                            { text = "quantity_13", value = 13 },
                            { text = "quantity_14", value = 14 },
                            { text = "quantity_15", value = 15 },
                            { text = "quantity_16", value = 16 },
                            { text = "quantity_17", value = 17 },
                            { text = "quantity_18", value = 18 },
                            { text = "quantity_19", value = 19 },
                            { text = "quantity_20", value = 20 },
                        },
                    },
                },
            },
            {
                setting_id = "group_advanced",
                type = "group",
                sub_widgets = {
                    {
                        setting_id = "show_unclassified_max",
                        type = "checkbox",
                        default_value = false,
                    },
                    {
                        setting_id = "test_refresh_notification",
                        type = "checkbox",
                        default_value = false,
                    },
                    {
                        setting_id = "debug_logging",
                        type = "checkbox",
                        default_value = false,
                    },
                },
            },
        },
    },
}
