return {
	mod_name = {
		en = "Multi-Bind",
		["zh-cn"] = "多重绑定",
		["zh-tw"] = "多重綁定",
		de = "Mehrfachbindung",
		fr = "Multi-Liaison",
		ru = "Мульти-связь",
	},
	mod_description = {
		en = 'An extra keybindings page to allow for multiple keybindings for a single action.\nAlso allows unbinding of default keybindings by binding with [DELETE]',
		["zh-cn"] = '一个额外的按键绑定页面，允许单个操作设置多个按键绑定。\n还可以通过按[DELETE]解除默认按键绑定',
		de = 'Eine zusätzliche Tastenzuweisungsseite, die mehrere Tastenzuweisungen für eine einzelne Aktion ermöglicht.\nErmöglicht auch das Aufheben von Standard-Tastenzuweisungen durch Binden mit [DELETE]',
		fr = 'Une page de raccourcis supplémentaires permettant de définir plusieurs raccourcis pour une seule action.\nPermet également de désactiver les raccourcis par défaut en les remplaçant par [DELETE]',
		ru = 'Дополнительная страница назначений клавиш, позволяющая назначать несколько клавиш для одного действия.\nТакже позволяет отменить привязку клавиш по умолчанию, назначив [DELETE]',
		["zh-tw"] = '額外的按鍵綁定頁面，允許為單個操作設置多個按鍵綁定。\n還可以通過綁定[DELETE]來解除預設按鍵綁定',
	},
	combat = {
		en = "Combat",
		["zh-cn"] = "战斗",
		de = "Kampf",
		fr = "Combat",
		ru = "Бой",
		["zh-tw"] = "戰鬥",
	},
	action_one = {
		en = "Primary Action",
		["zh-cn"] = "主要动作",
		de = "Primäre Aktion",
		fr = "Action principale",
		ru = "Основное действие",
		["zh-tw"] = "主要動作",
	},
	action_two = {
		en = "Secondary Action",
		["zh-cn"] = "次要动作",
		de = "Sekundäre Aktion",
		fr = "Action secondaire",
		ru = "Вторичное действие",
		["zh-tw"] = "次要動作",
	},
	weapon_extra = {
		en = "Weapon Special Action",
		["zh-cn"] = "武器特殊动作",
		de = "Waffenspezialaktion",
		fr = "Action spéciale de l'arme",
		ru = "Особое действие оружия",
		["zh-tw"] = "武器特殊動作",
	},
	interact = {
		en = "Interact",
		["zh-cn"] = "互动",
		de = "Interagieren",
		fr = "Interagir",
		ru = "Взаимодействие",
		["zh-tw"] = "互動",
	},
	interact_inspect = {
		en = "Inspect Operative",
		["zh-cn"] = "检查操作员",
		["zh-tw"] = "檢查操作者",
		de = "Operative inspizieren",
		fr = "Inspecter l'opérateur",
		ru = "Осмотреть оперативника",
	},
	wield_1 = {
		en = "Wield Primary Weapon",
		["zh-cn"] = "使用主要武器",
		de = "Primärwaffe führen",
		fr = "Manier l'arme principale",
		ru = "Использовать основное оружие",
	},
	wield_2 = {
		en = "Wield Secondary Weapon",
		["zh-cn"] = "使用次要武器",
		["zh-tw"] = "使用次要武器",
		de = "Sekundärwaffe führen",
		fr = "Manier l'arme secondaire",
		ru = "Использовать вторичное оружие",
	},
	wield_3 = {
		en = "Wield Large Item",
		["zh-cn"] = "使用大型物品",
		["zh-tw"] = "使用大型物品",
		de = "Großes Objekt führen",
		fr = "Manier un grand objet",
		ru = "Использовать крупный предмет",
	},
	wield_4 = {
		en = "Wield Small Item",
		["zh-cn"] = "使用小型物品",
		["zh-tw"] = "使用小型物品",
		de = "Kleines Objekt führen",
		fr = "Manier un petit objet",
		ru = "Использовать мелкий предмет",
	},
	wield_5 = {
		en = "Wield Auspex",
		["zh-cn"] = "使用感应器",
		["zh-tw"] = "使用感應器",
		de = "Auspex führen",
		fr = "Manier l'Auspex",
		ru = "Использовать ауспекс",
	},
	quick_wield = {
		en = "Swap Weapon",
		["zh-cn"] = "切换武器",
		["zh-tw"] = "切換武器",
		de = "Waffe wechseln",
		fr = "Changer d'arme",
		ru = "Сменить оружие",
	},
	wield_scroll_down = {
		en = "Wield Previous Item",
		["zh-cn"] = "使用上一个物品",
		["zh-tw"] = "使用上一個物品",
		de = "Vorheriges Objekt führen",
		fr = "Manier l'objet précédent",
		ru = "Использовать предыдущий предмет",
	},
	wield_scroll_up = {
		en = "Wield Next Item",
		["zh-cn"] = "使用下一个物品",
		["zh-tw"] = "使用下一個物品",
		de = "Nächstes Objekt führen",
		fr = "Manier l'objet suivant",
		ru = "Использовать следующий предмет",
	},
	weapon_reload = {
		en = "Reload Weapon",
		["zh-cn"] = "重新装填武器",
		["zh-tw"] = "重新裝填武器",
		de = "Waffe nachladen",
		fr = "Recharger l'arme",
		ru = "Перезарядить оружие",
	},
	grenade_ability = {
		en = "Activate Blitz",
		["zh-cn"] = "激活闪电战",
		["zh-tw"] = "啟動閃電戰",
		de = "Blitz aktivieren",
		fr = "Activer le Blitz",
		ru = "Активировать Блиц",
	},
	combat_ability = {
		en = "Activate Ability",
		["zh-cn"] = "激活技能",
		["zh-tw"] = "啟動技能",
		de = "Fähigkeit aktivieren",
		fr = "Activer la capacité",
		ru = "Активировать способность",
	},
	smart_tag = {
		en = "Tag",
		["zh-cn"] = "标记",
		["zh-tw"] = "標記",
		de = "Markieren",
		fr = "Marquer",
		ru = "Пометить",
	},
	com_wheel = {
		en = "Open Com Wheel",
		["zh-cn"] = "打开通信轮",
		["zh-tw"] = "打開通訊面板",
		de = "Kommandorad öffnen",
		fr = "Ouvrir la roue de communication",
		ru = "Открыть колесо команд",
	},
	tactical_overlay = {
		en = "Open Tactical Overlay",
		["zh-cn"] = "打开战术覆盖",
		["zh-tw"] = "打開戰術畫面",
		de = "Taktische Überlagerung öffnen",
		fr = "Ouvrir la superposition tactique",
		ru = "Открыть тактический интерфейс",
	},
	weapon_inspect = {
		en = "Inspect Weapon",
		["zh-cn"] = "检查武器",
		["zh-tw"] = "檢查武器",
		de = "Waffe inspizieren",
		fr = "Inspecter l'arme",
		ru = "Осмотреть оружие",
	},
	spectate_next = {
		en = "Spectate Next Player",
		["zh-cn"] = "观察下一个玩家",
		["zh-tw"] = "觀看下一個玩家",
		de = "Nächsten Spieler beobachten",
		fr = "Observer le joueur suivant",
		ru = "Наблюдать за следующим игроком",
	},
	voip_push_to_talk = {
		en = "Push to Talk",
		["zh-cn"] = "按键说话",
		["zh-tw"] = "按鍵說話",
		de = "Push to Talk",
		fr = "Appuyer pour parler",
		ru = "Нажми чтобы говорить",
	},
	hotkeys = {
		en = "Hotkeys",
		["zh-cn"] = "快捷键",
		["zh-tw"] = "快捷鍵",
		de = "Hotkeys",
		fr = "Raccourcis",
		ru = "Горячие клавиши",
	},
	hotkey_inventory = {
		en = "View Wargear",
		["zh-cn"] = "查看装备",
		["zh-tw"] = "檢視裝備",
		de = "Ausrüstung anzeigen",
		fr = "Voir l'équipement",
		ru = "Просмотр снаряжения",
	},
	interface = {
		en = "Interface",
		["zh-cn"] = "界面",
		["zh-tw"] = "介面",
		de = "Schnittstelle",
		fr = "Interface",
		ru = "Интерфейс",
	},
	show_chat = {
		en = "Show Chat",
		["zh-cn"] = "显示聊天",
		["zh-tw"] = "顯示聊天",
		de = "Chat anzeigen",
		fr = "Afficher le chat",
		ru = "Показать чат",
	},
	movement = {
		en = "Movement",
		["zh-cn"] = "移动",
		["zh-tw"] = "移動",
		de = "Bewegung",
		fr = "Mouvement",
		ru = "Движение",
	},
	keyboard_move_forward = {
		en = "Move Forward",
		["zh-cn"] = "前进",
		["zh-tw"] = "前進",
		de = "Vorwärts bewegen",
		fr = "Avancer",
		ru = "Двигаться вперёд",
	},
	keyboard_move_backward = {
		en = "Move Backward",
		["zh-cn"] = "后退",
		["zh-tw"] = "後退",
		de = "Rückwärts bewegen",
		fr = "Reculer",
		ru = "Двигаться назад",
	},
	keyboard_move_left = {
		en = "Move Left",
		["zh-cn"] = "左移",
		["zh-tw"] = "左移",
		de = "Nach links bewegen",
		fr = "Se déplacer à gauche",
		ru = "Двигаться влево",
	},
	keyboard_move_right = {
		en = "Move Right",
		["zh-cn"] = "右移",
		["zh-tw"] = "右移",
		de = "Nach rechts bewegen",
		fr = "Se déplacer à droite",
		ru = "Двигаться вправо",
	},
	dodge = {
		en = "Dodge",
		["zh-cn"] = "闪避",
		["zh-tw"] = "閃避",
		de = "Ausweichen",
		fr = "Esquiver",
		ru = "Уклонение",
	},
	jump = {
		en = "Jump",
		["zh-cn"] = "跳跃",
		["zh-tw"] = "跳躍",
		de = "Springen",
		fr = "Sauter",
		ru = "Прыгать",
	},
	crouch = {
		en = "Crouch",
		["zh-cn"] = "蹲下",
		["zh-tw"] = "蹲下",
		de = "Ducken",
		fr = "S'accroupir",
		ru = "Присесть",
	},
	sprint = {
		en = "Sprint",
		["zh-cn"] = "冲刺",
		["zh-tw"] = "衝刺",
		de = "Sprinten",
		fr = "Sprinter",
		ru = "Бег",
	},
}
