local mod = get_mod("TeammateHealthbars")

local widgets = {
	{
		setting_id = "feature_toggles",
		type = "group",
		sub_widgets = {
			{
				setting_id = "Refresh_Bars",
				type = "checkbox",
				default_value = false,
			},
			{
				setting_id = "show_teammate_healthbars",
				type = "checkbox",
				default_value = true,
			},
			{
				setting_id = "show_teammate_names", 
				type = "checkbox",
				default_value = true,
			},
			{
				setting_id = "show_health_bar",
				type = "checkbox", 
				default_value = true,
			},
			{
				setting_id = "show_toughness_bar",
				type = "checkbox",
				default_value = true,
			},
		
		},
	},
	{
		setting_id = "display_settings",
		type = "group",
		sub_widgets = {
			 {
				setting_id = "healthbar_height",
   				 type = "numeric",
   				 default_value = 81,
  				  range = {50, 500},
			 },
			{
				setting_id = "healthbar_size", 
   				 type = "numeric",
  				 default_value = 70,
  				  range = {30, 300},
			},
			{
				setting_id = "healthbar_opacity",
  				  type = "numeric", 
 				   default_value = 50,
    				range = {0, 100},
			},
			{
				setting_id = "max_distance",
				type = "numeric",
				default_value = 50,
				range = {10, 100},
			},
		
		},
	},
	{
		setting_id = "color_settings", 
		type = "group",
		sub_widgets = {
			{
				setting_id = "health_color_healthy",
				type = "dropdown",
				default_value = "green",
				options = {
					{text = "Green", value = "green"},
					{text = "Lime", value = "lime"},
					{text = "Forest Green", value = "forest_green"},
					{text = "Blue", value = "blue"},
					{text = "Light Blue", value = "light_blue"},
					{text = "Dark Blue", value = "dark_blue"},
					{text = "White", value = "white"},
					{text = "Light Gray", value = "light_gray"},
					{text = "Yellow", value = "yellow"},
					{text = "Gold", value = "gold"},
					{text = "Cyan", value = "cyan"},
					{text = "Teal", value = "teal"},
				},
			},
			{
				setting_id = "health_color_low",
				type = "dropdown", 
				default_value = "yellow",
				options = {
					{text = "Yellow", value = "yellow"},
					{text = "Gold", value = "gold"},
					{text = "Orange", value = "orange"},
					{text = "Dark Orange", value = "dark_orange"},
					{text = "Red", value = "red"},
					{text = "Light Red", value = "light_red"},
					{text = "Pink", value = "pink"},
					{text = "Magenta", value = "magenta"},
					{text = "White", value = "white"},
					{text = "Light Gray", value = "light_gray"},
				},
			},
			{
				setting_id = "health_color_critical",
				type = "dropdown",
				default_value = "red", 
				options = {
					{text = "Red", value = "red"},
					{text = "Dark Red", value = "dark_red"},
					{text = "Crimson", value = "crimson"},
					{text = "Light Red", value = "light_red"},
					{text = "Orange", value = "orange"},
					{text = "Dark Orange", value = "dark_orange"},
					{text = "Yellow", value = "yellow"},
					{text = "Pink", value = "pink"},
					{text = "Magenta", value = "magenta"},
					{text = "Purple", value = "purple"},
					{text = "White", value = "white"},
				},
			},
			{
				setting_id = "toughness_color",
				type = "dropdown",
				default_value = "blue",
				options = {
					{text = "Blue", value = "blue"},
					{text = "Light Blue", value = "light_blue"},
					{text = "Dark Blue", value = "dark_blue"},
					{text = "Cyan", value = "cyan"},
					{text = "Teal", value = "teal"},
					{text = "Aqua", value = "aqua"},
					{text = "Purple", value = "purple"},
					{text = "Violet", value = "violet"},
					{text = "Indigo", value = "indigo"},
					{text = "Magenta", value = "magenta"},
					{text = "Pink", value = "pink"},
					{text = "White", value = "white"},
					{text = "Light Gray", value = "light_gray"},
					{text = "Silver", value = "silver"},
				},
			},
			{
				setting_id = "frame_color",
				type = "dropdown",
				default_value = "bronze",
				options = {
					{text = "Bronze", value = "bronze"},
					{text = "Gold", value = "gold"},
					{text = "Silver", value = "silver"},
					{text = "White", value = "white"},
					{text = "Light Gray", value = "light_gray"},
					{text = "Dark Gray", value = "dark_gray"},
					{text = "Red", value = "red"},
					{text = "Dark Red", value = "dark_red"},
					{text = "Orange", value = "orange"},
					{text = "Yellow", value = "yellow"},
					{text = "Green", value = "green"},
					{text = "Blue", value = "blue"},
					{text = "Purple", value = "purple"},
					{text = "Cyan", value = "cyan"},
					{text = "Black", value = "black"},
				},
			},
			{
				setting_id = "name_color",
				type = "dropdown",
				default_value = "parchment",
				options = {
					{text = "Parchment", value = "parchment"},
					{text = "White", value = "white"},
					{text = "Light Gray", value = "light_gray"},
					{text = "Silver", value = "silver"},
					{text = "Gold", value = "gold"},
					{text = "Yellow", value = "yellow"},
					{text = "Orange", value = "orange"},
					{text = "Red", value = "red"},
					{text = "Pink", value = "pink"},
					{text = "Purple", value = "purple"},
					{text = "Blue", value = "blue"},
					{text = "Light Blue", value = "light_blue"},
					{text = "Cyan", value = "cyan"},
					{text = "Green", value = "green"},
					{text = "Lime", value = "lime"},
				},
			},
		},
	},
	{
		setting_id = "debug_settings",
		type = "group", 
		sub_widgets = {
			{
				setting_id = "show_debug_info",
				type = "checkbox",
				default_value = false,
			},
			{
				setting_id = "show_startup_messages",
				type = "checkbox",
				default_value = true,
			},
		},
	},
}

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = widgets,
	},
}