return {
	mod_name = {
		en = "Numeric UI",
		ru = "Числовой интерфейс",
		["zh-cn"] = "数显界面",
		["zh-tw"] = "數位化介面",
	},
	mod_description = {
		en = "Adds numbers to your HUD",
		["zh-cn"] = "在 HUD 上显示数字",
		ru = "Numeric UI - Добавляет цифры в ваш интерфейс",
		["zh-tw"] = "在 HUD 上顯示數字",
	},
	ability_items = {
		en = "Ability Cooldown HUD",
		["zh-cn"] = "技能冷却 HUD",
		ru = "Интерфейс перезарядки способностей",
		["zh-tw"] = "技能冷卻 HUD",
	},
	player_ammo_items = {
		en = "Ammo HUD",
		["zh-cn"] = "弹药 HUD",
		ru = "Интерфейс боеприпасов",
		["zh-tw"] = "彈藥 HUD",
	},
	dodge_count_items = {
		en = "Dodge Count HUD",
		["zh-cn"] = "闪避计数 HUD",
		ru = "Интерфейс счётчика уклонений",
		["zh-tw"] = "閃避計數 HUD",
	},
	team_hud_items = {
		en = "Team HUD",
		["zh-cn"] = "团队 HUD",
		ru = "Интерфейс команды",
		["zh-tw"] = "團隊 HUD",
	},
	health_text = {
		en = "Show health text",
		["zh-cn"] = "显示生命值",
		ru = "Показывать текст здоровья",
		["zh-tw"] = "顯示生命值",
	},
	toughness_text = {
		en = "Show toughness text",
		["zh-cn"] = "显示韧性值",
		ru = "Показывать текст стойкости",
		["zh-tw"] = "顯示韌性值",
	},
	ability_cd_bar = {
		en = "Show team's ability cooldown as progress bar",
		["zh-cn"] = "显示团队技能冷却进度条",
		ru = "Показывать время восст. способности команды в виде полосы прогреccа",
		["zh-tw"] = "顯示團隊技能冷卻進度條",
	},
	ability_cd_text = {
		en = "Show team's ability cooldown as numeric counter",
		["zh-cn"] = "显示团队技能冷却计数器",
		ru = "Показывать время восстановления способности команды в виде числа",
		["zh-tw"] = "顯示團隊技能冷卻計數器",
	},
	level = {
		en = "Show level",
		["zh-cn"] = "显示等级",
		ru = "Показывать уровень",
		["zh-tw"] = "顯示等級",
	},
	ammo_text = {
		en = "Show ammo text",
		["zh-cn"] = "显示弹药量",
		ru = "Показывать текст боеприпасов",
		["zh-tw"] = "顯示彈藥量",
	},
	peril_icon = {
		en = "Show peril icon",
		["zh-cn"] = "显示危机值图标",
		ru = "Показывать значок опасности",
		["zh-tw"] = "顯示危機值圖示",
	},
	max_ammo_text = {
		en = "Show maximum ammo text",
		["zh-cn"] = "显示最大弹药量",
		ru = "Показывать текст максимума боеприпасов",
		["zh-tw"] = "顯示最大彈藥量",
	},
	show_ammo_icon = {
		en = "Show icon for your own ammo",
		["zh-cn"] = "显示自己的弹药图标",
		ru = "Показывать иконку ваших боеприпасов",
		["zh-tw"] = "顯示自己的彈藥圖示",
	},
	show_munitions_gained = {
		en = "Show amount of ammo and grenades gained",
		["zh-cn"] = "显示获取的弹药数和手雷数",
		ru = "Показывать количество полученных боеприпасов и гранат",
		["zh-tw"] = "顯示獲得的彈藥數和手榴彈數",
	},
	ammo_as_percent = {
		en = "Show ammo as percent",
		["zh-cn"] = "弹药量以百分比显示",
		ru = "Показывать боеприпасы в процентах",
		["zh-tw"] = "彈藥量以百分比顯示",
	},
	show_ammo_amount_from_packs = {
		en = "Show ammo amount from packs and tins",
		["zh-cn"] = "显示弹药包内的弹药数",
		ru = "Показывать количество боеприпасов в контейнерах и коробках",
		["zh-tw"] = "顯示彈藥包內的彈藥數",
	},
	dodge_count = {
		en = "Show dodge count",
		["zh-cn"] = "显示闪避计数",
		ru = "Показывать количество уклонений",
		["zh-tw"] = "顯示閃避計數",
	},
	debug_dodge_count = {
		en = "Show debug dodge info",
		["zh-cn"] = "显示闪避调试信息",
		ru = "Показывать отладочную информацию уклонений",
		["zh-tw"] = "顯示閃避除錯資訊",
	},
	ability_cooldown_format = {
		en = "Ability cooldown format",
		["zh-cn"] = "主动能力冷却显示格式",
		ru = "Формат перезарядки способностей",
		["zh-tw"] = "技能冷卻顯示格式",
	},
	percent = {
		en = "Percent",
		["zh-cn"] = "百分比",
		ru = "Проценты",
		["zh-tw"] = "百分比",
	},
	timer = {
		en = "Timer",
		["zh-cn"] = "等待时间",
		ru = "Таймер",
		["zh-tw"] = "等待時間",
	},
	none = {
		en = "None",
		["zh-cn"] = "不显示",
		ru = "Нет",
		["zh-tw"] = "不顯示",
	},
	dodges_count_up = {
		en = "Dodges count up",
		["zh-cn"] = "正向显示闪避次数",
		ru = "Счётчик уклонений увеличивается",
		["zh-tw"] = "正向顯示閃避次數",
	},
	show_dodge_count_for_infinite_dodge = {
		en = "Show dodge count for infinite dodge weapons",
		["zh-cn"] = "无闪避上限的武器也显示闪避次数",
		ru = "Показывать количество уклонений для оружия с бесконечным уклонением",
		["zh-tw"] = "無閃避上限的武器也顯示閃避次數",
	},
	disable_ability_background_progress = {
		en = "Disable ability background progress",
		["zh-cn"] = "禁用主动能力冷却图标彩色进度条",
		ru = "Отключить визуальное увеличение шкалы способности на фоне",
		["zh-tw"] = "禁用技能背景冷卻進度條",
	},
	show_max_ammo_as_percent = {
		en = "Show max ammo as percent",
		["zh-cn"] = "最大弹药量以百分比显示",
		ru = "Показать максимальный боезапас в процентах",
		["zh-tw"] = "最大彈藥量以百分比顯示",
	},
	mission_timer = {
		en = "Mission Timer",
		["zh-cn"] = "任务计时器",
		ru = "Таймер миссии",
		["zh-tw"] = "任務計時器",
	},
	show_mission_timer = {
		en = "Show mission timer",
		["zh-cn"] = "显示任务计时器",
		ru = "Показать таймер миссии",
		["zh-tw"] = "顯示任務計時器",
	},
	mission_timer_in_overlay = {
		en = "Only in the overlay",
		["zh-cn"] = "仅在战术覆盖内显示",
		ru = "Только в оверлее",
		["zh-tw"] = "僅在戰術覆蓋中顯示",
	},
	nameplates = {
		en = "Nameplates",
		["zh-cn"] = "名称标签",
		ru = "Таблички с именами",
		["zh-tw"] = "名稱標籤",
	},
	archetype_icons_in_nameplates = {
		en = "Use class icons in nameplates",
		["zh-cn"] = "在名称标签内使用职业图标",
		ru = "Использовать значки классов в табличках с именами",
		["zh-tw"] = "在名稱標籤內使用職業圖示",
	},
	color_nameplate = {
		en = "Colour nameplate text same as icon",
		ru = "Цвет текста таблички с именем совпадает с цветом значка",
		["zh-cn"] = "使名称标签文本与图标颜色相同",
		["zh-tw"] = "名稱標籤文字與圖示顏色相同",
	},
	loading_screens = {
		en = "Loading screens",
		ru = "Экран загрузки",
		["zh-cn"] = "加载界面",
		["zh-tw"] = "加載畫面",
		mission_title_on_intro = {
			en = "Show mission title on loading screen",
			ru = "Показывать название миссии на экране загрузки",
			["zh-cn"] = "在加载界面显示任务详情",
			["zh-tw"] = "在加載畫面顯示任務標題",
		},
		show_efficient_dodges = {
			en = "Show number of efficient dodges",
			["zh-cn"] = "显示有效闪避数",
			["zh-tw"] = "顯示有效閃避次數",
			ru = "Показывать количество\nэффективных уклонений",
		},
		fade_out_max_dodges = {
			en = "Fade out when at max dodges",
			["zh-cn"] = "最大闪避数时隐藏",
			["zh-tw"] = "達到最大閃避次數時隱藏",
			ru = "Скрывать при максимальном количестве уклонений",
		},
		peril_text = {
			en = "Show peril percent text",
			["zh-cn"] = "显示危机值百分比文本",
			["zh-tw"] = "顯示反噬擲百分比文字",
			ru = "Показывать проценты угрозы",
		},
		pickup_settings = {
			en = "Pickups",
			["zh-cn"] = "拾取物",
			["zh-tw"] = "拾取物",
			ru = "Размещаемые объекты",
		},
		show_medical_crate_radius = {
			en = "Show medical crate radius",
			["zh-cn"] = "显示医疗箱范围",
			["zh-tw"] = "顯示醫療箱範圍",
			ru = "Показывать радиус медицинского контейнера",
		},
		show_medical_crate_radius_description = {
			en = "INCREASES MEMORY USE!",
			["zh-cn"] = "会增加内存占用！",
			["zh-tw"] = "會增加記憶體使用量！",
			ru = "УВЕЛИЧИВАЕТ ИСПОЛЬЗОВАНИЕ ПАМЯТИ!",
		},
		boss_health_settings = {
			en = "Boss health",
			["zh-cn"] = "Boss 生命值",
			["zh-tw"] = "Boss 生命值",
			ru = "Здоровье босса",
		},
		show_boss_health_numbers = {
			en = "Show boss health numbers",
			["zh-cn"] = "显示 Boss 生命值数字",
			["zh-tw"] = "顯示 Boss 生命值數字",
			ru = "Показывать цифры здоровья босса",
		},
		marker_settings = {
			en = "Marker settings",
			["zh-cn"] = "标记设置",
			["zh-tw"] = "標記設定",
		},
		show_ping_skull = {
			en = "Show tag skull",
			["zh-cn"] = "显示标记骷髅图标",
			["zh-tw"] = "顯示標記骷髏圖示",
		},
		show_vet_ping_skull = {
			en = "Show Veteran tag skull",
			["zh-cn"] = "显示老兵标记骷髅图标",
			["zh-tw"] = "顯示老兵標記骷髏圖示",
		},
	}
}
