return {
	mod_name = {
		en = "Machine God's Beacon",
		["zh-cn"] = "万机之神的灯塔",
		["zh-tw"] = "萬機之神的燈塔",
		ru = "Маяк Бога-Машины",
		de = "Leuchtfeuer des Maschinengottes",
		fr = "Balise du Dieu-Machine",
		es = "Faro del Dios Máquina",
	},
	mod_description = {
		en = "By invocation of the Machine God, the lumen-spirits of the habitat are awakened.",
		["zh-cn"] = "藉万机之神的召唤，栖息地的光魂已然苏醒。",
		["zh-tw"] = "藉由祈求萬機之神，棲息地的流明之靈甦醒了。",
		ru = "По призыву Бога-Машины пробуждаются люмен-духи обители.",
		de = "Durch Anrufung des Maschinengottes erwachen die Lumen-Geister der Behausung.",
		fr = "Par l'invocation du Dieu-Machine, les esprits-lumen de l'habitat s'éveillent.",
		es = "Por invocación del Dios Máquina, los espíritus-lumen del hábitat despiertan.",
	},
	light_group = {
		en = "Light Control",
		["zh-cn"] = "灯光控制",
		["zh-tw"] = "燈光控制",
		ru = "Управление светом",
		de = "Lichtsteuerung",
		fr = "Contrôle des lumières",
		es = "Control de luces",
	},
	flicker_group = {
		en = "Flicker Settings",
		["zh-cn"] = "闪烁设置",
		["zh-tw"] = "閃爍設定",
		ru = "Настройки мерцания",
		de = "Flacker-Einstellungen",
		fr = "Paramètres de scintillement",
		es = "Ajustes de parpadeo",
	},
	environment_group = {
		en = "Environment Control",
		["zh-cn"] = "环境控制",
		["zh-tw"] = "環境控制",
		ru = "Управление окружением",
		de = "Umgebungssteuerung",
		fr = "Contrôle de l'environnement",
		es = "Control del entorno",
	},
	debug_group = {
		en = "Debug",
		["zh-cn"] = "调试",
		["zh-tw"] = "除錯",
		ru = "Отладка",
		de = "Debug",
		fr = "Débogage",
		es = "Depuración",
	},
	mode_none = {
		en = "Off",
		["zh-cn"] = "关闭",
		["zh-tw"] = "關閉",
		ru = "Выкл",
		de = "Aus",
		fr = "Désactivé",
		es = "Desactivado",
	},
	mode_all = {
		en = "All Missions",
		["zh-cn"] = "所有任务",
		["zh-tw"] = "所有任務",
		ru = "Все миссии",
		de = "Alle Missionen",
		fr = "Toutes les missions",
		es = "Todas las misiones",
	},
	mode_normal = {
		en = "Normal Missions Only",
		["zh-cn"] = "仅普通任务",
		["zh-tw"] = "僅一般任務",
		ru = "Только обычные",
		de = "Nur normale Missionen",
		fr = "Missions normales uniquement",
		es = "Solo misiones normales",
	},
	mode_modified = {
		en = "Special Missions Only",
		["zh-cn"] = "仅特殊任务",
		["zh-tw"] = "僅特殊任務",
		ru = "Только особые",
		de = "Nur Spezialmissionen",
		fr = "Missions spéciales uniquement",
		es = "Solo misiones especiales",
	},
	light_control_mode_title = {
		en = "Light Control",
		["zh-cn"] = "灯光控制",
		["zh-tw"] = "燈光控制",
		ru = "Управление светом",
		de = "Lichtsteuerung",
		fr = "Contrôle des lumières",
		es = "Control de luces",
	},
	light_control_mode_tooltip = {
		en = "Apply light adjustments to missions. Off = disabled, All = all missions, Normal = normal missions only, Special = Lights Out/Ventilation Purge only",
		["zh-cn"] = "在任务中应用灯光调整。关闭 = 禁用，所有 = 全部任务，普通 = 仅普通任务，特殊 = 仅熄灯/通风净化",
		["zh-tw"] = "將燈光調整套用於任務。關閉 = 停用，所有 = 所有任務，一般 = 僅一般任務，特殊 = 僅熄燈/通風淨化",
		ru = "Применить настройки света к миссиям. Выкл = отключено, Все = все миссии, Обычные = только обычные, Особые = только Lights Out/Ventilation Purge",
		de = "Lichtanpassungen auf Missionen anwenden. Aus = deaktiviert, Alle = alle Missionen, Normal = nur normale Missionen, Spezial = nur Lights Out/Ventilation Purge",
		fr = "Appliquer les ajustements de lumière aux missions. Désactivé = inactif, Toutes = toutes les missions, Normales = missions normales uniquement, Spéciales = Lights Out/Ventilation Purge uniquement",
		es = "Aplicar ajustes de luz a las misiones. Desactivado = inactivo, Todas = todas las misiones, Normales = solo misiones normales, Especiales = solo Lights Out/Ventilation Purge",
	},
	environment_control_mode_title = {
		en = "Block Darkness/Fog",
		["zh-cn"] = "阻挡黑暗/迷雾",
		["zh-tw"] = "阻擋黑暗/霧氣",
		ru = "Блокировка тьмы/тумана",
		de = "Dunkelheit/Nebel blockieren",
		fr = "Bloquer obscurité/brouillard",
		es = "Bloquear oscuridad/niebla",
	},
	environment_control_mode_tooltip = {
		en = "Block darkness and fog effects (requires reload). Off = disabled, All = all missions, Normal = normal missions only, Special = Lights Out/Ventilation Purge only",
		["zh-cn"] = "阻挡黑暗和迷雾效果（需重新加载）。关闭 = 禁用，所有 = 全部任务，普通 = 仅普通任务，特殊 = 仅熄灯/通风净化",
		["zh-tw"] = "阻擋黑暗與霧氣效果（需要重新載入）。關閉 = 停用，所有 = 所有任務，一般 = 僅一般任務，特殊 = 僅熄燈/通風淨化",
		ru = "Блокировать эффекты тьмы и тумана (требуется перезагрузка). Выкл = отключено, Все = все миссии, Обычные = только обычные, Особые = только Lights Out/Ventilation Purge",
		de = "Dunkelheits- und Nebeleffekte blockieren (Neuladen erforderlich). Aus = deaktiviert, Alle = alle Missionen, Normal = nur normale Missionen, Spezial = nur Lights Out/Ventilation Purge",
		fr = "Bloquer les effets d'obscurité et de brouillard (rechargement requis). Désactivé = inactif, Toutes = toutes les missions, Normales = missions normales uniquement, Spéciales = Lights Out/Ventilation Purge uniquement",
		es = "Bloquear efectos de oscuridad y niebla (requiere recarga). Desactivado = inactivo, Todas = todas las misiones, Normales = solo misiones normales, Especiales = solo Lights Out/Ventilation Purge",
	},
	light_percentage_title = {
		en = "Light Percentage",
		["zh-cn"] = "灯光百分比",
		["zh-tw"] = "燈光百分比",
		ru = "Процент освещения",
		de = "Lichtanteil",
		fr = "Pourcentage de lumières",
		es = "Porcentaje de luces",
	},
	light_percentage_tooltip = {
		en = "Percentage of lights to enable (0-100)",
		["zh-cn"] = "启用灯光的百分比 (0-100)",
		["zh-tw"] = "啟用燈光的百分比 (0-100)",
		ru = "Процент включённых источников света (0-100)",
		de = "Prozentsatz der aktiven Lichter (0-100)",
		fr = "Pourcentage de lumières activées (0-100)",
		es = "Porcentaje de luces activas (0-100)",
	},
	light_selection_title = {
		en = "Light Selection Mode",
		["zh-cn"] = "灯光选择模式",
		["zh-tw"] = "燈光選擇模式",
		ru = "Режим выбора",
		de = "Auswahlmodus",
		fr = "Mode de sélection",
		es = "Modo de selección",
	},
	light_selection_tooltip = {
		en = "How to select which lights are enabled",
		["zh-cn"] = "决定启用哪些灯光的方式",
		["zh-tw"] = "如何選擇哪些燈光被啟用",
		ru = "Как выбираются активные источники света",
		de = "Bestimmt, welche Lichter aktiviert werden",
		fr = "Détermine quelles lumières sont activées",
		es = "Determina qué luces se activan",
	},
	light_selection_incremental = {
		en = "Incremental",
		["zh-cn"] = "递增",
		["zh-tw"] = "遞增",
		ru = "Последовательно",
		de = "Fortlaufend",
		fr = "Progressif",
		es = "Progresivo",
	},
	light_selection_alternating = {
		en = "Alternating",
		["zh-cn"] = "交替",
		["zh-tw"] = "交替",
		ru = "Чередование",
		de = "Abwechselnd",
		fr = "Alterné",
		es = "Alterno",
	},
	light_selection_spread = {
		en = "Spread",
		["zh-cn"] = "分散",
		["zh-tw"] = "分散",
		ru = "Равномерно",
		de = "Verteilt",
		fr = "Réparti",
		es = "Distribuido",
	},
	light_selection_random = {
		en = "Random",
		["zh-cn"] = "随机",
		["zh-tw"] = "隨機",
		ru = "Случайно",
		de = "Zufällig",
		fr = "Aléatoire",
		es = "Aleatorio",
	},
	light_state_title = {
		en = "Light Mode",
		["zh-cn"] = "灯光模式",
		["zh-tw"] = "燈光模式",
		ru = "Режим света",
		de = "Lichtmodus",
		fr = "Mode d'éclairage",
		es = "Modo de luz",
	},
	light_state_tooltip = {
		en = "How lights should behave",
		["zh-cn"] = "灯光的行为方式",
		["zh-tw"] = "燈光應如何運作",
		ru = "Поведение источников света",
		de = "Verhalten der Lichter",
		fr = "Comportement des lumières",
		es = "Comportamiento de las luces",
	},
	light_state_static = {
		en = "Static",
		["zh-cn"] = "静态",
		["zh-tw"] = "靜態",
		ru = "Статично",
		de = "Statisch",
		fr = "Statique",
		es = "Estático",
	},
	light_state_flicker = {
		en = "Flicker",
		["zh-cn"] = "闪烁",
		["zh-tw"] = "閃爍",
		ru = "Мерцание",
		de = "Flackern",
		fr = "Scintillement",
		es = "Parpadeo",
	},
	light_state_flicker_cascade = {
		en = "Cascade Flicker",
		["zh-cn"] = "级联闪烁",
		["zh-tw"] = "級聯閃爍",
		ru = "Каскадное мерцание",
		de = "Kaskaden-Flackern",
		fr = "Scintillement en cascade",
		es = "Parpadeo en cascada",
	},
	light_state_flicker_random = {
		en = "Random Flicker",
		["zh-cn"] = "随机闪烁",
		["zh-tw"] = "隨機閃爍",
		ru = "Случайное мерцание",
		de = "Zufälliges Flackern",
		fr = "Scintillement aléatoire",
		es = "Parpadeo aleatorio",
	},
	flicker_default_title = {
		en = "Flicker Default State",
		["zh-cn"] = "闪烁默认状态",
		["zh-tw"] = "閃爍預設狀態",
		ru = "Состояние по умолчанию",
		de = "Standard-Flickerzustand",
		fr = "État par défaut",
		es = "Estado por defecto",
	},
	flicker_default_tooltip = {
		en = "Default state for lights when flickering",
		["zh-cn"] = "灯光闪烁时的默认状态",
		["zh-tw"] = "燈光閃爍時的預設狀態",
		ru = "Исходное состояние света при мерцании",
		de = "Ausgangszustand der Lichter beim Flackern",
		fr = "État initial des lumières lors du scintillement",
		es = "Estado inicial de las luces al parpadear",
	},
	flicker_default_on = {
		en = "On",
		["zh-cn"] = "开",
		["zh-tw"] = "開啟",
		ru = "Вкл",
		de = "An",
		fr = "Allumé",
		es = "Encendido",
	},
	flicker_default_off = {
		en = "Off",
		["zh-cn"] = "关",
		["zh-tw"] = "關閉",
		ru = "Выкл",
		de = "Aus",
		fr = "Éteint",
		es = "Apagado",
	},
	flicker_interval_title = {
		en = "Flicker Interval (seconds)",
		["zh-cn"] = "闪烁间隔（秒）",
		["zh-tw"] = "閃爍間隔（秒）",
		ru = "Интервал мерцания (сек)",
		de = "Flacker-Intervall (Sekunden)",
		fr = "Intervalle de scintillement (secondes)",
		es = "Intervalo de parpadeo (segundos)",
	},
	flicker_interval_tooltip = {
		en = "Time between flicker events",
		["zh-cn"] = "闪烁事件之间的时间间隔",
		["zh-tw"] = "閃爍事件之間的時間",
		ru = "Время между вспышками",
		de = "Zeit zwischen Flackervorgängen",
		fr = "Temps entre les scintillements",
		es = "Tiempo entre parpadeos",
	},
	flicker_percentage_title = {
		en = "Flicker Percentage",
		["zh-cn"] = "闪烁百分比",
		["zh-tw"] = "閃爍百分比",
		ru = "Процент мерцания",
		de = "Flacker-Prozentsatz",
		fr = "Pourcentage de scintillement",
		es = "Porcentaje de parpadeo",
	},
	flicker_percentage_tooltip = {
		en = "Percentage of lights to flicker each interval",
		["zh-cn"] = "每次间隔闪烁的灯光百分比",
		["zh-tw"] = "每個間隔閃爍的燈光百分比",
		ru = "Процент мерцающих источников света за интервал",
		de = "Prozentsatz der flackernden Lichter pro Intervall",
		fr = "Pourcentage de lumières qui scintillent par intervalle",
		es = "Porcentaje de luces que parpadean por intervalo",
	},
	flicker_duration_title = {
		en = "Flicker Duration (seconds)",
		["zh-cn"] = "闪烁持续时间（秒）",
		["zh-tw"] = "閃爍持續時間（秒）",
		ru = "Длительность мерцания (сек)",
		de = "Flacker-Dauer (Sekunden)",
		fr = "Durée du scintillement (secondes)",
		es = "Duración del parpadeo (segundos)",
	},
	flicker_duration_tooltip = {
		en = "How long each flicker lasts",
		["zh-cn"] = "每次闪烁持续的时间",
		["zh-tw"] = "每次閃爍持續多久",
		ru = "Продолжительность каждой вспышки",
		de = "Wie lange jedes Flackern dauert",
		fr = "Durée de chaque scintillement",
		es = "Duración de cada parpadeo",
	},
	flicker_cooldown_title = {
		en = "Flicker Cooldown (seconds)",
		["zh-cn"] = "闪烁冷却（秒）",
		["zh-tw"] = "閃爍冷卻（秒）",
		ru = "Перезарядка мерцания (сек)",
		de = "Flacker-Abklingzeit (Sekunden)",
		fr = "Recharge du scintillement (secondes)",
		es = "Reutilización del parpadeo (segundos)",
	},
	flicker_cooldown_tooltip = {
		en = "Minimum time before a light can flicker again",
		["zh-cn"] = "灯光再次闪烁前的最短等待时间",
		["zh-tw"] = "燈光再次閃爍前的最短時間",
		ru = "Минимальное время до повторного мерцания",
		de = "Mindestzeit, bevor ein Licht erneut flackern kann",
		fr = "Temps minimum avant qu'une lumière puisse scintiller à nouveau",
		es = "Tiempo mínimo antes de que una luz pueda parpadear de nuevo",
	},
	enable_stutter_title = {
		en = "Enable Stutter",
		["zh-cn"] = "启用频闪",
		["zh-tw"] = "啟用頻閃",
		ru = "Включить дребезг",
		de = "Stottern aktivieren",
		fr = "Activer le clignotement",
		es = "Activar titubeo",
	},
	enable_stutter_tooltip = {
		en = "Add rapid on/off stuttering to flicker effect",
		["zh-cn"] = "为闪烁效果添加快速开关的频闪",
		["zh-tw"] = "為閃爍效果新增快速開/關頻閃",
		ru = "Добавить быстрое переключение к эффекту мерцания",
		de = "Fügt schnelles An/Aus-Stottern zum Flackereffekt hinzu",
		fr = "Ajoute un clignotement rapide à l'effet de scintillement",
		es = "Añade un titubeo rápido al efecto de parpadeo",
	},
	stutter_count_title = {
		en = "Stutter Count",
		["zh-cn"] = "频闪次数",
		["zh-tw"] = "頻閃次數",
		ru = "Число циклов",
		de = "Stotter-Anzahl",
		fr = "Nombre de clignotements",
		es = "Cantidad de titubeos",
	},
	stutter_count_tooltip = {
		en = "Number of rapid on/off cycles during stutter",
		["zh-cn"] = "频闪期间的快速开关循环次数",
		["zh-tw"] = "頻閃期間快速開/關的循環次數",
		ru = "Количество быстрых циклов вкл/выкл",
		de = "Anzahl der schnellen An/Aus-Zyklen beim Stottern",
		fr = "Nombre de cycles marche/arrêt rapides",
		es = "Número de ciclos rápidos de encendido/apagado",
	},
	debug_mode_title = {
		en = "Debug Mode",
		["zh-cn"] = "调试模式",
		["zh-tw"] = "除錯模式",
		ru = "Режим отладки",
		de = "Debug-Modus",
		fr = "Mode débogage",
		es = "Modo depuración",
	},
	debug_mode_tooltip = {
		en = "Enable verbose logging for troubleshooting",
		["zh-cn"] = "启用详细日志以便排查问题",
		["zh-tw"] = "啟用詳細日誌以進行故障排除",
		ru = "Включить подробное логирование для диагностики",
		de = "Aktiviert ausführliche Protokollierung zur Fehlerbehebung",
		fr = "Active la journalisation détaillée pour le dépannage",
		es = "Activa el registro detallado para solucionar problemas",
	},
}