return {
	mod_name = {
		en = "Share Talents",
		["zh-cn"] = "天赋加点分享",
		ru = "Делитесь билдами",
		["zh-tw"] = "天賦配點分享",
	},
	mod_description = {
		en = "Copy, paste and share talents builds.",
		["zh-cn"] = "复制、粘贴和分享天赋加点。",
		ru = "Share Talents - Копируйте, вставляйте и делитесь текущим билдом талантов.",
		["zh-tw"] = "複製、貼上及分享天賦配點。",
	},
	msg_view_copied = {
		en = "Talents copied!",
		["zh-cn"] = "已复制天赋加点！",
		ru = "Таланты скопированы!",
		["zh-tw"] = "已複製天賦配點！",
	},
	msg_view_pasted = {
		en = "Talents pasted!",
		["zh-cn"] = "已粘贴天赋加点！",
		ru = "Таланты вставлены!",
		["zh-tw"] = "已貼上天賦配點！",
	},
	msg_code_copied = {
		en = "Talents code copied! This code may expire after a game update",
		["zh-cn"] = "已复制天赋加点代码！此代码可能会在游戏更新后失效",
		ru = "Код билда скопирован! Срок действия этого кода может истечь после обновления игры.",
		["zh-tw"] = "已複製天賦配點程式碼！此程式碼可能會在遊戲更新後失效",
	},
	msg_code_applied = {
		en = "Talents code applied!",
		["zh-cn"] = "已应用天赋加点代码！",
		ru = "Код билда применён!",
		["zh-tw"] = "已套用天賦配點！",
	},
	err_unknown = {
		en = "Error: unknown error",
		["zh-cn"] = "错误：未知错误",
		ru = "Ошибка: неизвестная ошибка",
		["zh-tw"] = "錯誤：未知錯誤",
	},
	err_invalid_talents = {
		en = "Error: current talents invalid",
		["zh-cn"] = "错误：当前天赋无效",
		ru = "Ошибка: текущие таланты недействительны",
		["zh-tw"] = "錯誤：目前天賦無效",
	},
	err_archetype_mismatch = {
		en = "Error: archetype mismatch",
		["zh-cn"] = "错误：职业不匹配",
		ru = "Ошибка: несоответствие архетипа",
		["zh-tw"] = "錯誤：職業不匹配",
	},
	err_invalid_code = {
		en = "Error: talents code invalid or expired",
		["zh-cn"] = "错误：天赋代码无效或已过期",
		ru = "Ошибка: код таланта недействителен или срок его действия истёк",
		["zh-tw"] = "錯誤：天賦配點無效或已過期",
	},
	err_argument = {
		en = "Error: command argument invalid",
		["zh-cn"] = "错误：命令参数无效",
		ru = "Ошибка: неверный аргумент команды",
		["zh-tw"] = "錯誤：指令參數無效",
	},
	err_clipboard_notfound = {
		en = "Error: no talents in the clipboard",
		["zh-cn"] = "错误：剪贴板中没有天赋",
		ru = "Ошибка: в буфере обмена нет скопированных талантов",
		["zh-tw"] = "錯誤：剪貼簿中沒有天賦",
	},
	widget__share_talents_copy = {
		en = "Copy Talents",
		["zh-cn"] = "复制天赋",
		ru = "Копировать билд",
		["zh-tw"] = "複製天賦",
	},
	widget__share_talents_paste = {
		en = "Paste Talents",
		["zh-cn"] = "粘贴天赋",
		ru = "Вставить билд",
		["zh-tw"] = "貼上天賦",
	},
}
