local mod = get_mod("FpsDoctor")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "show_overlay",
				type = "checkbox",
				default_value = true,
				tooltip = "show_overlay_desc",
			},
			{
				setting_id = "toggle_overlay_key",
				type = "keybind",
				default_value = { "f6" },
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_overlay",
				tooltip = "toggle_overlay_key_desc",
			},
			{
				setting_id = "anchor",
				type = "dropdown",
				default_value = "top_left",
				tooltip = "anchor_desc",
				options = {
					{ text = "anchor_top_left",     value = "top_left" },
					{ text = "anchor_top_right",    value = "top_right" },
					{ text = "anchor_bottom_left",  value = "bottom_left" },
					{ text = "anchor_bottom_right", value = "bottom_right" },
				},
			},
			{
				setting_id = "pos_x",
				type = "numeric",
				default_value = 24,
				range = { 0, 600 },
				tooltip = "pos_x_desc",
			},
			{
				setting_id = "pos_y",
				type = "numeric",
				default_value = 24,
				range = { 0, 600 },
				tooltip = "pos_y_desc",
			},
			{
				setting_id = "overlay_scale",
				type = "numeric",
				default_value = 100,
				range = { 50, 300 },
				tooltip = "overlay_scale_desc",
			},
			{
				setting_id = "opacity_text",
				type = "numeric",
				default_value = 100,
				range = { 10, 100 },
				tooltip = "opacity_text_desc",
			},
			{
				setting_id = "opacity_bg",
				type = "numeric",
				default_value = 60,
				range = { 0, 100 },
				tooltip = "opacity_bg_desc",
			},

			{
				setting_id = "show_fps",
				type = "checkbox",
				default_value = true,
				tooltip = "show_fps_desc",
			},
			{
				setting_id = "show_low",
				type = "checkbox",
				default_value = true,
				tooltip = "show_low_desc",
			},
			{
				setting_id = "show_frame_ms",
				type = "checkbox",
				default_value = true,
				tooltip = "show_frame_ms_desc",
			},
			{
				setting_id = "show_heap",
				type = "checkbox",
				default_value = true,
				tooltip = "show_heap_desc",
			},
			{
				setting_id = "show_mission",
				type = "checkbox",
				default_value = true,
				tooltip = "show_mission_desc",
			},
			{
				setting_id = "show_session",
				type = "checkbox",
				default_value = false,
				tooltip = "show_session_desc",
			},
			{
				setting_id = "show_proc_mem",
				type = "checkbox",
				default_value = false,
				tooltip = "show_proc_mem_desc",
			},
			{
				setting_id = "restart_advice_mb",
				type = "numeric",
				default_value = 512,
				range = { 0, 2048 },
				tooltip = "restart_advice_mb_desc",
			},
			{
				setting_id = "show_hitch",
				type = "checkbox",
				default_value = true,
				tooltip = "show_hitch_desc",
			},
			{
				setting_id = "hitch_ms",
				type = "numeric",
				default_value = 50,
				range = { 20, 200 },
				tooltip = "hitch_ms_desc",
			},
			{
				setting_id = "show_gc_mode",
				type = "checkbox",
				default_value = true,
				tooltip = "show_gc_mode_desc",
			},

			{
				setting_id = "reset_stats_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "reset_stats",
				tooltip = "reset_stats_key_desc",
			},
			{
				setting_id = "auto_reset",
				type = "checkbox",
				default_value = false,
				tooltip = "auto_reset_desc",
			},
			{
				setting_id = "auto_reset_minutes",
				type = "numeric",
				default_value = 10,
				range = { 1, 60 },
				tooltip = "auto_reset_minutes_desc",
			},

			{
				setting_id = "gc_mode",
				type = "dropdown",
				default_value = "aggressive",
				tooltip = "gc_mode_desc",
				options = {
					{ text = "gc_mode_off",        value = "off" },
					{ text = "gc_mode_map_only",   value = "map_only" },
					{ text = "gc_mode_balanced",   value = "balanced" },
					{ text = "gc_mode_pacer",      value = "pacer" },
					{ text = "gc_mode_aggressive", value = "aggressive" },
				},
			},
			{
				setting_id = "smooth_collect",
				type = "checkbox",
				default_value = true,
				tooltip = "smooth_collect_desc",
			},
			{
				setting_id = "gc_pause",
				type = "numeric",
				default_value = 700,
				range = { 100, 1000 },
				tooltip = "gc_pause_desc",
			},
			{
				setting_id = "gc_stepmul",
				type = "numeric",
				default_value = 300,
				range = { 100, 1000 },
				tooltip = "gc_stepmul_desc",
			},
			{
				setting_id = "gc_budget_us",
				type = "numeric",
				default_value = 1500,
				range = { 200, 4000 },
				tooltip = "gc_budget_us_desc",
			},
			{
				setting_id = "mem_type",
				type = "dropdown",
				default_value = "auto",
				tooltip = "mem_type_desc",
				options = {
					-- The speed list is only consulted for a hand-picked generation, so
					-- it stays hidden while "auto" measures the machine instead.
					{ text = "mem_type_auto", value = "auto" },
					{ text = "mem_type_ddr3", value = "ddr3", show_widgets = { 1 } },
					{ text = "mem_type_ddr4", value = "ddr4", show_widgets = { 1 } },
					{ text = "mem_type_ddr5", value = "ddr5", show_widgets = { 1 } },
				},
				sub_widgets = {
					{
						setting_id = "mem_mts",
						type = "dropdown",
						default_value = 3200,
						tooltip = "mem_mts_desc",
						options = {
							{ text = "mem_mts_1333", value = 1333 },
							{ text = "mem_mts_1600", value = 1600 },
							{ text = "mem_mts_1866", value = 1866 },
							{ text = "mem_mts_2133", value = 2133 },
							{ text = "mem_mts_2400", value = 2400 },
							{ text = "mem_mts_2666", value = 2666 },
							{ text = "mem_mts_3000", value = 3000 },
							{ text = "mem_mts_3200", value = 3200 },
							{ text = "mem_mts_3600", value = 3600 },
							{ text = "mem_mts_4000", value = 4000 },
							{ text = "mem_mts_4800", value = 4800 },
							{ text = "mem_mts_5200", value = 5200 },
							{ text = "mem_mts_5600", value = 5600 },
							{ text = "mem_mts_6000", value = 6000 },
							{ text = "mem_mts_6400", value = 6400 },
							{ text = "mem_mts_7200", value = 7200 },
							{ text = "mem_mts_8000", value = 8000 },
						},
					},
				},
			},
			{
				setting_id = "hw_profile",
				type = "dropdown",
				default_value = "advise",
				tooltip = "hw_profile_desc",
				options = {
					{ text = "hw_profile_advise", value = "advise" },
					{ text = "hw_profile_apply",  value = "apply" },
					{ text = "hw_profile_off",    value = "off" },
				},
			},
			{
				setting_id = "vram_gb",
				type = "dropdown",
				default_value = 0,
				tooltip = "vram_gb_desc",
				options = {
					{ text = "vram_gb_auto", value = 0 },
					{ text = "vram_gb_2",  value = 2 },
					{ text = "vram_gb_3",  value = 3 },
					{ text = "vram_gb_4",  value = 4 },
					{ text = "vram_gb_6",  value = 6 },
					{ text = "vram_gb_8",  value = 8 },
					{ text = "vram_gb_10", value = 10 },
					{ text = "vram_gb_12", value = 12 },
					{ text = "vram_gb_16", value = 16 },
					{ text = "vram_gb_24", value = 24 },
				},
			},
			{
				setting_id = "periodic_minutes",
				type = "numeric",
				default_value = 10,
				range = { 1, 30 },
				tooltip = "periodic_minutes_desc",
			},
			{
				setting_id = "threshold_mb",
				type = "numeric",
				default_value = 1024,
				range = { 256, 2048 },
				tooltip = "threshold_mb_desc",
			},
			{
				setting_id = "heap_ceiling_mb",
				type = "numeric",
				default_value = 1024,
				range = { 512, 4096 },
				tooltip = "heap_ceiling_mb_desc",
			},
			{
				setting_id = "deep_clean",
				type = "checkbox",
				default_value = true,
				tooltip = "deep_clean_desc",
			},
			{
				setting_id = "deep_clean_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "deep_clean_now",
				tooltip = "deep_clean_key_desc",
			},
			{
				setting_id = "engine_gc",
				type = "checkbox",
				default_value = true,
				tooltip = "engine_gc_desc",
			},
			{
				setting_id = "uncap_menus",
				type = "checkbox",
				default_value = false,
				tooltip = "uncap_menus_desc",
			},
			{
				setting_id = "fast_loading",
				type = "checkbox",
				default_value = false,
				tooltip = "fast_loading_desc",
			},
			{
				setting_id = "mod_profiler",
				type = "checkbox",
				default_value = false,
				tooltip = "mod_profiler_desc",
			},
			{
				setting_id = "fix_hud_leaks",
				type = "checkbox",
				default_value = true,
				tooltip = "fix_hud_leaks_desc",
			},
			{
				setting_id = "menu_drain",
				type = "checkbox",
				default_value = false,
				tooltip = "menu_drain_desc",
			},
			{
				setting_id = "dmf_release",
				type = "checkbox",
				default_value = false,
				tooltip = "dmf_release_desc",
			},
			{
				setting_id = "mute_telemetry",
				type = "checkbox",
				default_value = false,
				tooltip = "mute_telemetry_desc",
			},
			{
				setting_id = "force_gc_key",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "force_gc",
				tooltip = "force_gc_key_desc",
			},
			{
				setting_id = "diag_log",
				type = "checkbox",
				default_value = false,
				tooltip = "diag_log_desc",
			},
			{
				setting_id = "silent",
				type = "checkbox",
				default_value = false,
				tooltip = "silent_desc",
			},
		},
	},
}
