local mod = get_mod("ImprovedHavocTags")

--[[
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Mod Name: Improved Havoc Tags                                                                                                    │
│ Mod Author: Brunin (brufgsilva on Nexus)																						   │
│ Version: 3.1																													   │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
--]]

local function get_color_string(color_name)
    local color = Color[color_name](255, true)
    return string.format("%d,%d,%d", color[2], color[3], color[4])
end

mod:add_global_localize_strings({
    loc_havoc_increased_difficulty_name = {
        en = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("increased_difficulty")) .. ")}" .. Localize("loc_havoc_increased_difficulty_name") .. "{#reset()}",
    },
    loc_havoc_highest_difficulty_name = {
        en = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("highest_difficulty")) .. ")}" .. Localize("loc_havoc_highest_difficulty_name") .. "{#reset()}",
    },
    loc_havoc_bolstering_enemies_name = {
        en = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}蠻橫敵軍(加防){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("bolstering_enemies")) .. ")}" .. Localize("loc_havoc_bolstering_enemies_name") .. "{#reset()}",
    },
    loc_havoc_encroaching_garden_name = {
        en = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Marked Healers{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Markierte Heiler{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Soigneurs Marqués{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Guaritori Segnati{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}표식된 치유사{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Sanadores Marcados{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}瘟疫袭来(回血){#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}蔓生花園(回血){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Помеченные целители{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}刻印のヒーラー{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Naznaczeni Uzdrowiciele{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("encroaching_garden")) .. ")}Curandeiros Marcados{#reset()}",
    },
    loc_havoc_mutator_enraged_name = {
        en = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Enraging Elites{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Wütende Eliten{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Élites Enragées{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Élite Furente{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}분노한 정예병{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Élites Enfurecidos{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}最后的钟声(狂暴){#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}背水一戰(狂暴){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Разъярённая элита{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}怒れる精鋭{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Wściekła Elita{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("enraged")) .. ")}Elites Enfurecidos{#reset()}",
    },
    loc_havoc_chaos_ritual_name = {
        en = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}萬惡儀式(宿主){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("chaos_ritual")) .. ")}" .. Localize("loc_havoc_chaos_ritual_name") .. "{#reset()}",
    },
    loc_havoc_armored_infected_name = {
        en = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}莫比亞21師(防彈){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("armored_infected")) .. ")}" .. Localize("loc_havoc_armored_infected_name") .. "{#reset()}",
    },
    loc_havoc_enemies_corrupted_name = {
        en = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}疫病蔓延(腐化){#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("enemies_corrupted")) .. ")}" .. Localize("loc_havoc_enemies_corrupted_name") .. "{#reset()}",
    },
    loc_havoc_enemies_parasite_headshot_name = {
        en = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("enemies_parasite_headshot")) .. ")}" .. Localize("loc_havoc_enemies_parasite_headshot_name") .. "{#reset()}",
    },
    loc_havoc_tougher_skin_name = {
        en = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("tougher_skin")) .. ")}" .. Localize("loc_havoc_tougher_skin_name") .. "{#reset()}",
    },
	loc_havoc_rotten_armor_name = {
        en = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("rotten_armor")) .. ")}" .. Localize("loc_havoc_rotten_armor_name") .. "{#reset()}",
    },
	loc_havoc_stimmed_minions_name = {
        en = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("stimmed_minions")) .. ")}" .. Localize("loc_havoc_stimmed_minions_name") .. "{#reset()}",
    },
    loc_circumstance_ember_title = {
        en = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("ember")) .. ")}" .. Localize("loc_circumstance_ember_title") .. "{#reset()}",
    },
    loc_circumstance_toxic_gas_title = {
        en = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("toxic_gas")) .. ")}" .. Localize("loc_circumstance_toxic_gas_title") .. "{#reset()}",
    },
    loc_circumstance_toxic_gas_cultist_grenadier_title = {
        en = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("toxic_gas_cultist_grenadier")) .. ")}" .. Localize("loc_circumstance_toxic_gas_cultist_grenadier_title") .. "{#reset()}",
    },
    loc_circumstance_ventilation_purge_title = {
        en = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("ventilation_purge")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_title") .. "{#reset()}",
    },
    loc_circumstance_ventilation_purge_with_snipers_title = {
        en = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("ventilation_purge_with_snipers")) .. ")}" .. Localize("loc_circumstance_ventilation_purge_with_snipers_title") .. "{#reset()}",
    },
    loc_circumstance_darkness_title = {
        en = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("darkness")) .. ")}" .. Localize("loc_circumstance_darkness_title") .. "{#reset()}",
    },
    loc_circumstance_darkness_hunting_grounds_title = {
        en = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        de = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        fr = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        it = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ko = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        es = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ["zh-cn"] = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ["zh-tw"] = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ru = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ja = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        pl = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
        ["pt-br"] = "{#color(" .. get_color_string(mod:get("darkness_hunting_grounds")) .. ")}" .. Localize("loc_circumstance_darkness_hunting_grounds_title") .. "{#reset()}",
    },
})