-- File: uptime\scripts\mods\uptime\uptime_localization.lua
local mod = get_mod("uptime"); if not mod then return end
local Localize = Localize
mod:add_global_localize_strings({
    loc_scan_folder = {
        en = "Scan Directory for Files",
        fr = "Analyser le dossier pour trouver des fichiers",
        it = "Scansiona la directory per i file",
        de = "Verzeichnis nach Dateien durchsuchen",
        es = "Escanear directorio en busca de archivos",
        pl = "Przeskanuj katalog w poszukiwaniu plików",
        ["pt-br"] = "Verificar diretório em busca de arquivos",
        ru = "Сканировать каталог на наличие файлов",
        ["zh-cn"] = "扫描目录中的文件",
        ja = "ディレクトリ内のファイルをスキャン",
        ko = "디렉터리에서 파일 스캔",
        ["zh-tw"] = "掃描目錄中的檔案",
    },
    loc_edit_note = {
        en = "Edit Note",
        fr = "Modifier la note",
        it = "Modifica nota",
        de = "Notiz bearbeiten",
        es = "Editar nota",
        pl = "Edytuj notatkę",
        ["pt-br"] = "Editar nota",
        ru = "Редактировать заметку",
        ["zh-cn"] = "编辑备注",
        ja = "メモを編集",
        ko = "메모 편집",
        ["zh-tw"] = "編輯備註",
    },
    loc_note_popup_description = {
        en = "Enter a short note for this history entry. Leave blank to clear the note.",
        fr = "Saisissez une courte note pour cette entrée d'historique. Laissez vide pour effacer la note.",
        it = "Inserisci una breve nota per questa voce della cronologia. Lascia vuoto per cancellare la nota.",
        de = "Gib eine kurze Notiz für diesen Verlaufseintrag ein. Leer lassen, um die Notiz zu löschen.",
        es = "Introduce una nota breve para esta entrada del historial. Déjalo en blanco para borrar la nota.",
        pl = "Wpisz krótką notatkę dla tego wpisu historii. Pozostaw puste, aby usunąć notatkę.",
        ["pt-br"] = "Insira uma nota curta para esta entrada do histórico. Deixe em branco para limpar a nota.",
        ru = "Введите короткую заметку для этой записи истории. Оставьте поле пустым, чтобы удалить заметку.",
        ["zh-cn"] = "输入此记录的简短备注。留空可清除备注。",
        ja = "この履歴項目の短いメモを入力します。空白のままにするとメモを消去します。",
        ko = "이 기록 항목에 대한 짧은 메모를 입력하세요. 비워 두면 메모가 지워집니다.",
        ["zh-tw"] = "輸入此記錄的簡短備註。留空可清除備註。",
    },
})

return {
    mission_duration = {
        -- first %s: mission time (format mm:ss)
        -- second %s: combat time (format mm:ss)
        -- third %s: combat percentage
        en = Localize("loc_interface_setting_chat_bubbles_lifetime_multiplier") ..
            ": " ..
            Localize("loc_hud_presence_mission") .. " %s - " .. Localize("loc_keybind_category_combat") .. " %s (%s)",
    },
    mod_name = { en = "Uptime 2" },
    mod_description = {
        en = "Tracks uptime of buffs.",
        fr = "Suit le temps d'activité des bonus.",
        it = "Tiene traccia del tempo di attività dei buff.",
        de = "Verfolgt die aktive Zeit von Buffs.",
        es = "Registra el tiempo activo de las mejoras.",
        pl = "Śledzi czas aktywności wzmocnień.",
        ["pt-br"] = "Rastreia o tempo de atividade dos bônus.",
        ru = "Отслеживает время действия усилений.",
        ["zh-cn"] = "追踪增益效果的持续时间",
        ja = "バフの稼働時間を記録します。",
        ko = "버프의 활성 시간을 추적합니다.",
        ["zh-tw"] = "追蹤增益效果的持續時間"
    },
    loc_uptime_header = {
        en = "Uptime",
        fr = "Temps actif",
        it = "Tempo attivo",
        de = "Aktivzeit",
        es = "Tiempo activo",
        pl = "Czas aktywności",
        ["pt-br"] = "Tempo ativo",
        ru = "Время действия",
        ["zh-cn"] = "持续时间",
        ja = "稼働時間",
        ko = "활성 시간",
        ["zh-tw"] = "持續時間",
    },
    loc_avg_stacks_header = {
        en = "Avg Stacks",
        fr = "Cumuls moy.",
        it = "Cariche medie",
        de = "Ø-Stapel",
        es = "Acum. medias",
        pl = "Śr. ładunki",
        ["pt-br"] = "Acúmulos médios",
        ru = "Средн. заряды",
        ["zh-cn"] = "平均层数",
        ja = "平均スタック",
        ko = "평균 중첩",
        ["zh-tw"] = "平均層數",
    },
    loc_percentage_per_stack = {
        en = "Uptime (by Stack)",
        fr = "Temps actif (par cumul)",
        it = "Tempo attivo (per carica)",
        de = "Aktivzeit (nach Stapel)",
        es = "Tiempo activo (por acumulación)",
        pl = "Czas aktywności według ładunków",
        ["pt-br"] = "Tempo ativo por acúmulo",
        ru = "Время действия по зарядам",
        ["zh-cn"] = "持续时间(按层数)",
        ja = "稼働時間（スタック別）",
        ko = "활성 시간(중첩별)",
        ["zh-tw"] = "持續時間(按層數)",
    },

    -- general settings
    delete_old_entries = {
        en = "Automatically Delete Old Files",
        fr = "Supprimer automatiquement les anciens fichiers",
        it = "Elimina automaticamente i vecchi file",
        de = "Alte Dateien automatisch löschen",
        es = "Eliminar automáticamente archivos antiguos",
        pl = "Automatycznie usuwaj stare pliki",
        ["pt-br"] = "Excluir arquivos antigos automaticamente",
        ru = "Автоматически удалять старые файлы",
        ["zh-cn"] = "自动删除旧文件",
        ja = "古いファイルを自動的に削除",
        ko = "오래된 파일 자동 삭제",
        ["zh-tw"] = "自動刪除舊檔案",
    },
    number_of_save_files = {
        en = "Number of Save Files to Keep",
        fr = "Nombre de fichiers de sauvegarde à conserver",
        it = "Numero di file di salvataggio da conservare",
        de = "Anzahl zu behaltender Speicherdateien",
        es = "Número de archivos guardados que conservar",
        pl = "Liczba plików zapisu do zachowania",
        ["pt-br"] = "Número de arquivos salvos a manter",
        ru = "Количество сохраняемых файлов",
        ["zh-cn"] = "要保留的保存文件数量",
        ja = "保持する保存ファイル数",
        ko = "보관할 저장 파일 수",
        ["zh-tw"] = "要保留的保存檔案數量",
    },
    legacy_history_compatibility = {
        en = "Legacy History Compatibility",
        fr = "Compatibilité avec l'ancien historique",
        it = "Compatibilità cronologia legacy",
        de = "Kompatibilität mit altem Verlauf",
        es = "Compatibilidad con historial antiguo",
        pl = "Zgodność ze starą historią",
        ["pt-br"] = "Compatibilidade com histórico antigo",
        ru = "Совместимость со старой историей",
        ["zh-cn"] = "旧版历史兼容性",
        ja = "旧履歴との互換性",
        ko = "이전 기록 호환성",
        ["zh-tw"] = "舊版歷史相容性",
    },
    legacy_history_compatibility_description = {
        en =
        "Allows Uptime to decode old history files that do not have metadata yet. Disable this if opening the history list still causes crashes.",
        fr =
        "Permet à Uptime de décoder les anciens fichiers d'historique qui n'ont pas encore de métadonnées. Désactivez cette option si l'ouverture de la liste d'historique provoque encore des plantages.",
        it =
        "Consente a Uptime di decodificare i vecchi file della cronologia che non hanno ancora metadati. Disattiva questa opzione se l'apertura dell'elenco della cronologia causa ancora crash.",
        de =
        "Erlaubt Uptime, alte Verlaufsdateien ohne Metadaten zu dekodieren. Deaktiviere dies, wenn das Öffnen der Verlaufsliste weiterhin Abstürze verursacht.",
        es =
        "Permite que Uptime decodifique archivos de historial antiguos que aún no tienen metadatos. Desactívalo si abrir la lista del historial sigue provocando cierres.",
        pl =
        "Pozwala Uptime dekodować stare pliki historii, które nie mają jeszcze metadanych. Wyłącz tę opcję, jeśli otwieranie listy historii nadal powoduje awarie.",
        ["pt-br"] =
        "Permite que o Uptime decodifique arquivos antigos de histórico que ainda não têm metadados. Desative se abrir a lista do histórico ainda causar travamentos.",
        ru =
        "Позволяет Uptime декодировать старые файлы истории, у которых ещё нет метаданных. Отключите, если открытие списка истории всё ещё вызывает сбои.",
        ["zh-cn"] = "允许 Uptime 解码尚未生成元数据的旧历史文件。如果打开历史列表仍会崩溃，请禁用此选项。",
        ja = "メタデータがまだない古い履歴ファイルを Uptime がデコードできるようにします。履歴リストを開くとまだクラッシュする場合は無効にしてください。",
        ko = "아직 메타데이터가 없는 이전 기록 파일을 Uptime이 디코드하도록 허용합니다. 기록 목록을 열 때 여전히 충돌이 발생하면 이 옵션을 끄세요.",
        ["zh-tw"] = "允許 Uptime 解碼尚未產生中繼資料的舊版歷史檔案。如果開啟歷史列表仍會當機，請停用此選項。",
    },

    -- dropdown options
    loc_dropdown_none = { en = Localize("loc_setting_com_wheel_tap_none") },
    loc_dropdown_time = { en = Localize("loc_interface_setting_chat_bubbles_lifetime_multiplier") },
    loc_dropdown_percentage = {
        en = "Percentage Only",
        fr = "Pourcentage uniquement",
        it = "Solo percentuale",
        de = "Nur Prozent",
        es = "Solo porcentaje",
        pl = "Tylko procent",
        ["pt-br"] = "Apenas porcentagem",
        ru = "Только процент",
        ["zh-cn"] = "仅百分比",
        ja = "割合のみ",
        ko = "백분율만",
        ["zh-tw"] = "僅百分比",
    },

    -- table columns & their settings
    show_uptime_mode = {
        en = "Total Uptime Display",
        fr = "Affichage du temps actif total",
        it = "Visualizzazione tempo attivo totale",
        de = "Anzeige der gesamten Aktivzeit",
        es = "Visualización del tiempo activo total",
        pl = "Wyświetlanie całkowitego czasu aktywności",
        ["pt-br"] = "Exibição do tempo ativo total",
        ru = "Отображение общего времени действия",
        ["zh-cn"] = "总持续时间显示",
        ja = "合計稼働時間の表示",
        ko = "총 활성 시간 표시",
        ["zh-tw"] = "總持續時間顯示",
    },
    loc_uptime_percentage_header = {
        en = "Uptime",
        fr = "Temps actif",
        it = "Tempo attivo",
        de = "Aktivzeit",
        es = "Tiempo activo",
        pl = "Czas aktywności",
        ["pt-br"] = "Tempo ativo",
        ru = "Время действия",
        ["zh-cn"] = "持续时间",
        ja = "稼働時間",
        ko = "활성 시간",
        ["zh-tw"] = "持續時間",
    },

    show_uptime_combat_mode = {
        en = "Combat Uptime Display",
        fr = "Affichage du temps actif en combat",
        it = "Visualizzazione tempo attivo in combattimento",
        de = "Anzeige der Aktivzeit im Kampf",
        es = "Visualización del tiempo activo en combate",
        pl = "Wyświetlanie czasu aktywności w walce",
        ["pt-br"] = "Exibição do tempo ativo em combate",
        ru = "Отображение времени действия в бою",
        ["zh-cn"] = "战斗持续时间显示",
        ja = "戦闘中の稼働時間表示",
        ko = "전투 중 활성 시간 표시",
        ["zh-tw"] = "戰鬥持續時間顯示",
    },
    loc_uptime_combat_header = {
        en = "Uptime (Combat)",
        fr = "Temps actif (combat)",
        it = "Tempo attivo (combattimento)",
        de = "Aktivzeit (Kampf)",
        es = "Tiempo activo (combate)",
        pl = "Czas aktywności (walka)",
        ["pt-br"] = "Tempo ativo (combate)",
        ru = "Время действия (бой)",
        ["zh-cn"] = "持续时间(战斗)",
        ja = "稼働時間（戦闘）",
        ko = "활성 시간(전투)",
        ["zh-tw"] = "持續時間(戰鬥)",
    },
    loc_uptime_combat_percentage_header = {
        en = "Uptime (Combat)",
        fr = "Temps actif (combat)",
        it = "Tempo attivo (combattimento)",
        de = "Aktivzeit (Kampf)",
        es = "Tiempo activo (combate)",
        pl = "Czas aktywności (walka)",
        ["pt-br"] = "Tempo ativo (combate)",
        ru = "Время действия (бой)",
        ["zh-cn"] = "持续时间(战斗)",
        ja = "稼働時間（戦闘）",
        ko = "활성 시간(전투)",
        ["zh-tw"] = "持續時間(戰鬥)",
    },

    show_combat_percentage_per_stack = {
        en = "Stack Distribution During Combat",
        fr = "Répartition des cumuls en combat",
        it = "Distribuzione delle cariche in combattimento",
        de = "Stapelverteilung im Kampf",
        es = "Distribución de acumulaciones en combate",
        pl = "Rozkład ładunków podczas walki",
        ["pt-br"] = "Distribuição de acúmulos em combate",
        ru = "Распределение зарядов в бою",
        ["zh-cn"] = "战斗中层数分布",
        ja = "戦闘中のスタック分布",
        ko = "전투 중 중첩 분포",
        ["zh-tw"] = "戰鬥中層數分布",
    },
    loc_combat_percentage_per_stack_header = {
        en = "Uptime (Combat) by Stack",
        fr = "Temps actif (combat) par cumul",
        it = "Tempo attivo (combattimento) per carica",
        de = "Aktivzeit (Kampf) nach Stapel",
        es = "Tiempo activo (combate) por acumulación",
        pl = "Czas aktywności w walce według ładunków",
        ["pt-br"] = "Tempo ativo (combate) por acúmulo",
        ru = "Время действия в бою по зарядам",
        ["zh-cn"] = "战斗持续时间(按层数)",
        ja = "稼働時間（戦闘、スタック別）",
        ko = "활성 시간(전투, 중첩별)",
        ["zh-tw"] = "戰鬥持續時間(按層數)",
    },

    show_combat_max_stack_mode = {
        en = "Time at Max Stacks (Combat) Display",
        fr = "Affichage du temps aux cumuls max. (combat)",
        it = "Visualizzazione tempo a cariche massime (combattimento)",
        de = "Anzeige der Zeit bei max. Stapeln (Kampf)",
        es = "Visualización del tiempo con acumulaciones máximas (combate)",
        pl = "Wyświetlanie czasu przy maks. ładunkach (walka)",
        ["pt-br"] = "Exibição do tempo com acúmulos máximos (combate)",
        ru = "Отображение времени при макс. зарядах (бой)",
        ["zh-cn"] = "战斗期间处于最大层数的显示",
        ja = "最大スタック時の時間表示（戦闘）",
        ko = "최대 중첩 시간 표시(전투)",
        ["zh-tw"] = "戰鬥期間處於最大層數的顯示",
    },
    loc_combat_time_at_max_stack_header = {
        en = "Time at max (combat)",
        fr = "Temps au max. (combat)",
        it = "Tempo al massimo (combattimento)",
        de = "Zeit bei Maximum (Kampf)",
        es = "Tiempo al máximo (combate)",
        pl = "Czas przy maksimum (walka)",
        ["pt-br"] = "Tempo no máximo (combate)",
        ru = "Время на максимуме (бой)",
        ["zh-cn"] = "最大层数时间(战斗)",
        ja = "最大時の時間（戦闘）",
        ko = "최대 중첩 시간(전투)",
        ["zh-tw"] = "最大層數時間(戰鬥)",
    },
    loc_combat_percentage_at_max_stack_header = {
        en = "Percentage at max (combat)",
        fr = "Pourcentage au max. (combat)",
        it = "Percentuale al massimo (combattimento)",
        de = "Prozent bei Maximum (Kampf)",
        es = "Porcentaje al máximo (combate)",
        pl = "Procent przy maksimum (walka)",
        ["pt-br"] = "Porcentagem no máximo (combate)",
        ru = "Процент на максимуме (бой)",
        ["zh-cn"] = "最大层数百分比(战斗)",
        ja = "最大時の割合（戦闘）",
        ko = "최대 중첩 비율(전투)",
        ["zh-tw"] = "最大層數百分比(戰鬥)",
    },

    show_average_stacks_combat = {
        en = "Average Stack Count During Combat",
        fr = "Nombre moyen de cumuls en combat",
        it = "Numero medio di cariche in combattimento",
        de = "Durchschnittliche Stapelanzahl im Kampf",
        es = "Cantidad media de acumulaciones en combate",
        pl = "Średnia liczba ładunków podczas walki",
        ["pt-br"] = "Contagem média de acúmulos em combate",
        ru = "Среднее число зарядов в бою",
        ["zh-cn"] = "战斗期间平均层数",
        ja = "戦闘中の平均スタック数",
        ko = "전투 중 평균 중첩 수",
        ["zh-tw"] = "戰鬥期間平均層數",
    },
    loc_average_stacks_combat_header = {
        en = "Average stack (combat)",
        fr = "Cumul moyen (combat)",
        it = "Carica media (combattimento)",
        de = "Ø-Stapel (Kampf)",
        es = "Acumulación media (combate)",
        pl = "Śr. ładunki (walka)",
        ["pt-br"] = "Acúmulo médio (combate)",
        ru = "Средн. заряд (бой)",
        ["zh-cn"] = "平均层数(战斗)",
        ja = "平均スタック（戦闘）",
        ko = "평균 중첩(전투)",
        ["zh-tw"] = "平均層數(戰鬥)",
    },

    track_damage = {
        en = "Scoreboard Mode",
        fr = "Mode tableau des scores",
        it = "Modalità tabellone",
        de = "Punktetafel-Modus",
        es = "Modo de marcador",
        pl = "Tryb tablicy wyników",
        ["pt-br"] = "Modo de placar",
        ru = "Режим таблицы счёта",
        ["zh-cn"] = "记分板模式",
        ja = "スコアボードモード",
        ko = "점수판 모드",
        ["zh-tw"] = "記分板模式",
    },


    loc_damage_dot = {
        en = "DOT",
        fr = "Dégâts sur la durée",
        it = "Danni nel tempo",
        de = "Schaden über Zeit",
        es = "Daño prolongado",
        pl = "Obrażenia w czasie",
        ["pt-br"] = "Dano ao longo do tempo",
        ru = "Урон со временем",
        ["zh-cn"] = "持续伤害",
        ja = "継続ダメージ",
        ko = "지속 피해",
        ["zh-tw"] = "持續傷害",
    },
    loc_uptime_command_toggle_tracking = {
        en = "Toggle uptime tracking",
        fr = "Activer/désactiver le suivi du temps actif",
        it = "Attiva/disattiva il tracciamento del tempo attivo",
        de = "Aktivzeit-Erfassung umschalten",
        es = "Activar/desactivar el seguimiento del tiempo activo",
        pl = "Przełącz śledzenie czasu aktywności",
        ["pt-br"] = "Alternar rastreamento de tempo ativo",
        ru = "Переключить отслеживание времени действия",
        ["zh-cn"] = "切换持续时间追踪",
        ja = "稼働時間の記録を切り替え",
        ko = "활성 시간 추적 전환",
        ["zh-tw"] = "切換持續時間追蹤",
    },
    loc_damage_horde = {
        en = "Horde",
        fr = "Horde",
        it = "Orda",
        de = "Horde",
        es = "Horda",
        pl = "Horda",
        ["pt-br"] = "Horda",
        ru = "Орда",
        ["zh-cn"] = "尸潮",
        ja = "ホード",
        ko = "호드",
        ["zh-tw"] = "屍潮",
    },
    loc_damage_elite = {
        en = "Elite",
        fr = "Élite",
        it = "Élite",
        de = "Elite",
        es = "Élite",
        pl = "Elita",
        ["pt-br"] = "Elite",
        ru = "Элита",
        ["zh-cn"] = "精英",
        ja = "エリート",
        ko = "정예",
        ["zh-tw"] = "精英",
    },
    loc_damage_special = {
        en = "Special",
        fr = "Spécialiste",
        it = "Specialista",
        de = "Spezialist",
        es = "Especialista",
        pl = "Specjalny",
        ["pt-br"] = "Especialista",
        ru = "Специалист",
        ["zh-cn"] = "专家",
        ja = "スペシャリスト",
        ko = "스페셜",
        ["zh-tw"] = "專家",
    },
    loc_damage_boss = {
        en = "Boss",
        fr = "Boss",
        it = "Boss",
        de = "Boss",
        es = "Jefe",
        pl = "Boss",
        ["pt-br"] = "Chefe",
        ru = "Босс",
        ["zh-cn"] = "首领",
        ja = "ボス",
        ko = "보스",
        ["zh-tw"] = "首領",
    },
    loc_damage_taken = {
        en = "Damage Taken",
        fr = "Dégâts subis",
        it = "Danni subiti",
        de = "Erlittener Schaden",
        es = "Daño recibido",
        pl = "Otrzymane obrażenia",
        ["pt-br"] = "Dano sofrido",
        ru = "Полученный урон",
        ["zh-cn"] = "承受伤害",
        ja = "被ダメージ",
        ko = "받은 피해",
        ["zh-tw"] = "承受傷害",
    },
    loc_times_assisted = {
        en = "Times Assisted",
        fr = "Aides reçues",
        it = "Assistenze ricevute",
        de = "Unterstützungen erhalten",
        es = "Veces asistido",
        pl = "Liczba asyst",
        ["pt-br"] = "Vezes auxiliado",
        ru = "Помощь получена",
        ["zh-cn"] = "被协助次数",
        ja = "救助された回数",
        ko = "도움받은 횟수",
        ["zh-tw"] = "被協助次數",
    },

    -- Ingame loc keys
    loc_note_empty_placeholder = { en = "--" },
    loc_uptime_save = { en = Localize("loc_confirm") },
    loc_note_save_failed = { en = Localize("loc_popup_header_error") },

    loc_track_damage_off = { en = Localize("loc_setting_nv_reflex_disabled") },

    loc_havoc_rank = { en = Localize("loc_havoc_name") .. " %d" },

    loc_loadout_blitz = { en = Localize("loc_tactical_overlay_build_blitz") },
    loc_loadout_ability = { en = Localize("loc_tactical_overlay_build_ability") },
    loc_loadout_aura = { en = Localize("loc_tactical_overlay_build_aura") },
    loc_loadout_keystone = { en = Localize("loc_glossary_talent_keystone") },
    loc_loadout_companion = { en = Localize("loc_companion_tutorial_adamant_name") },
    loc_loadout_weapon = { en = Localize("loc_achievement_category_weapons_label") },

    open_uptime_history = { en = Localize("loc_objective_cm_archives_outside_header") },

    save_files_options = { en = Localize("loc_achievement_mission_scripture_recovery_name") },

    data_display_settings = { en = Localize("loc_credits_view_data_analyst_title") },
    track_meat_grinder = { en = Localize("loc_training_grounds_view_display_name") },
    loc_dropdown_both = { en = Localize("loc_setting_dodge_stamina_hud_both_always") },

    loc_talent_header = { en = Localize("loc_talent_view_display_name") },
    loc_percentage_at_max_stacks_header = { en = Localize("loc_expertise_crafting_modifiers_max") },
    loc_unknown_blessing = { en = Localize("loc_settings_menu_group_other_settings") },
    loc_scoreboard_local_player = { en = Localize("loc_character_view_display_name") },
    loc_scoreboard_team = { en = Localize("loc_achievement_category_teamplay_label") },
    loc_damage_melee = { en = Localize("loc_setting_melee") },
    loc_damage_ranged = { en = Localize("loc_setting_ranged") },
    loc_damage_blitz = { en = Localize("loc_tactical_overlay_build_blitz") },
    loc_damage_total = { en = Localize("loc_stat_display_damage_dealt") },

    loc_track_damage_view = { en = Localize("loc_achievement_mission_scripture_recovery_name") },
    loc_track_damage_view_and_tactical = { en = Localize("loc_achievement_mission_scripture_recovery_name") .. " + " .. Localize("loc_keyboard_input_tab") },
    loc_track_damage_view_end = { en = Localize("loc_achievement_mission_scripture_recovery_name") .. " + " .. Localize("loc_hud_presence_end_of_round") },
    loc_track_damage_view_tactical_end = { en = Localize("loc_achievement_mission_scripture_recovery_name") .. " + " .. Localize("loc_keyboard_input_tab") .. " + " .. Localize("loc_hud_presence_end_of_round") },

    end_view_scoreboard_position = { en = Localize("loc_hud_presence_end_of_round") .. ": " .. Localize("loc_setting_com_wheel_tap_ping") },
    loc_end_view_scoreboard_position_down = { en = Localize("loc_alias_view_navigate_down") },
    loc_end_view_scoreboard_position_up = { en = Localize("loc_alias_view_navigate_up") },
}
