return {
	mod_title = {
		en = "Servo Friend",
		de = "Servo Freund",
		["zh-cn"] = "我的伺服颅骨",
		["zh-tw"] = "我的伺服器顱骨助手",
		ru = "Серводруг",
	},
	mod_description = {
		en = "Adds a servo skull that follows you.",
		de = "Fügt einen Servo-Kopf hinzu, der dir folgt.",
		["zh-cn"] = "现在一个伺服颅骨会成为你的伙伴，照亮你前方的道路",
		["zh-tw"] = "現在一個伺服器顱骨將會成為你的隨行助手，照亮你前進的道路",
		ru = "Servo Friend - Добавляет сервочереп, который следует за вами.",
	},

	group_focus = {
		en = "Focus",
		de = "Fokus",
		["zh-cn"] = "目标锁定系统",
		["zh-tw"] = "目標鎖定系統",
		ru = "Фокусировка",
	},
	mod_option_focus_tagged_enemies = {
		en = "Focus Tagged Enemies",
		de = "Markierte Gegner fokussieren",
		["zh-cn"] = "锁定标记目标",
		["zh-tw"] = "鎖定已標記的敵人",
		ru = "Фокусировка на отмеченных врагах",
	},
	mod_option_focus_tagged_enemies_tooltip = {
		en = "Focus Tagged Enemies",
		de = "Markierte Gegner fokussieren",
		["zh-cn"] = "伺服颅骨会照亮一个已被战术标记的敌人",
		["zh-tw"] = "伺服器顱骨將會照亮已被標記的敵人",
		ru = "Серводруг подсвечивает отмеченных врагов для вас.",
	},
	mod_option_focus_tagged_items = {
		en = "Focus Tagged Items",
		de = "Markierte Items fokussieren",
		["zh-cn"] = "锁定标记物品",
		["zh-tw"] = "鎖定已標記的物品",
		ru = "Фокусировка на отмеченных предметах",
	},
	mod_option_focus_tagged_items_tooltip = {
		en = "Focus Tagged Items",
		de = "Markierte Items fokussieren",
		["zh-cn"] = "伺服颅骨会照亮被战术标记的重要物品（弹药、材料、医疗箱等）",
		["zh-tw"] = "伺服器顱骨將會照亮已被標記的重要物品（彈藥、素材、醫療箱等）",
		ru = "Серводруг подсвечивает отмеченные предметы для вас.",
	},
	mod_option_focus_world_markers = {
		en = "Focus world markers",
		de = "Welt-Markierungen fokussieren",
		["zh-cn"] = "环境标记追踪‌",
		["zh-tw"] = "場景標記追蹤",
		ru = "Фокусировка на метках на земле",
	},
	mod_option_focus_world_markers_tooltip = {
		en = "Focus locational markers that have been created in the world.",
		de = "Fokussiere markierte Positionen die in der Welt erstellt wurden.",
		["zh-cn"] = "伺服颅骨会照亮被任意玩家标记的位置（长按标记后的表情：去这里）‌",
		["zh-tw"] = "伺服器顱骨將會照亮被任何玩家標記的位置（長按標記後的表情：來這裡）",
		ru = "Серводруг подсвечивает места, отмеченные вами.",
	},
	mod_option_only_own_tags = {
		en = "Only own Tags and Markers",
		de = "Nur eigene Markierungen",
		["zh-cn"] = "仅限个人标记‌",
		["zh-tw"] = "僅追蹤自己的標記",
		ru = "Только свои метки",
	},
	mod_option_only_own_tags_tooltip = {
		en = "The servo friend only reacts to your own tags and markers.",
		de = "Der Servo-Freund reagiert nur auf eigene Markierungen.",
		["zh-cn"] = "伺服颅骨仅响应玩家自身设置的标记（长按标记后的表情：去这里）‌",
		["zh-tw"] = "伺服器顱骨只會回應你自己設置的標記（長按標記後的表情：來這裡）",
		ru = "Серводруг реагирует только на ваши собственные метки.",
	},
	mod_option_use_free_roaming = {
		en = "Use Roaming Mode",
		de = "Bewegungsmodus",
		["zh-cn"] = "启用巡航模式",
		["zh-tw"] = "啟用巡邏模式",
	},
	mod_option_use_free_roaming_tooltip = {
		en = "The servo friend will roam around the player instead of hovering above.",
		de = "Der Servo-Freund wandert in einem Bereich um den Spieler anstatt darüber zu schweben.",
		["zh-cn"] = "切换伺服颅骨的伴随逻辑：从定点悬停改为动态环绕巡航", 
		["zh-tw"] = "改變伺服器顱骨的行為邏輯：從固定懸停切換為動態環繞巡邏",
	},
	mod_option_use_roaming_area = {
		en = "Use Roaming Area",
		de = "Bewegungsbereich nutzen",
		["zh-cn"] = "启用活动区域限制",
		["zh-tw"] = "啟用活動範圍限制",
	},
	mod_option_use_roaming_area_tooltip = {
		en = "The servo friend will roam in a certain area.",
		de = "Der Servo-Freund wandert in einem bestimmten Bereich.",
		["zh-cn"] = "激活后伺服颅骨将在预设的战术区域内自主巡航",
		["zh-tw"] = "啟用後伺服器顱骨將在預設的作戰區域內自主巡邏",
	},
	mod_option_roaming_area = {
		en = "Roaming Area",
		de = "Bewegungsbereich",
		["zh-cn"] = "战术巡航半径",
		["zh-tw"] = "巡邏範圍半徑",
	},
	mod_option_roaming_area_tooltip = {
		en = "The area that the servo friend has to roam in.",
		de = "Der Bereich in dem der Servo-Freund wandert.",
		["zh-cn"] = "设定伺服颅骨的最大巡航活动范围（单位：米）",
		["zh-tw"] = "設定伺服器顱骨的最大巡邏活動範圍（單位：公尺）",
	},
	mod_option_focus_self_on_block = {
		en = "Self-Focus on Block",
		de = "Selbst-Fokus beim Blocken",
		["zh-cn"] = "格挡时照亮自身",
		["zh-tw"] = "格擋時照亮自身",
		ru = "Фокусировка на вас при блоке",
	},
	mod_option_focus_self_on_block_tooltip = {
		en = "Servo friend shines light on you from above.",
		de = "Servo Freund scheint Licht von oben auf dich.",
		["zh-cn"] = "玩家格挡时，伺服颅骨从上方会照亮自己",
		["zh-tw"] = "玩家格擋時，伺服器顱骨會從上方照亮自己",
		ru = "Серводруг подсвечивает вас сверху.",
	},
	mod_option_focus_self_on_vent = {
		en = "Self-Focus on Vent",
		de = "Selbst-Fokus beim Venting",
		["zh-cn"] = "散热时照亮自身",
		["zh-tw"] = "排熱時照亮自身",
		ru = "Фокусировка на вас при сбросе перегрева",
	},
	mod_option_focus_self_on_vent_tooltip = {
		en = "Focus Self on Vent",
		de = "Selbst auf Ventil fokussieren",
		["zh-cn"] = "灵能者散热时，伺服颅骨从上方会照亮自己",
		["zh-tw"] = "靈能者排熱時，伺服器顱骨會從上方照亮自己",
		ru = "Серводруг подсвечивает вас сверху, когда вы сбрасываете перегрев.",
	},

	group_flashlight = {
		en = "Flashlight",
		de = "Lichtquelle",
		["zh-cn"] = "照明系统",
		["zh-tw"] = "照明系統",
		ru = "Фонарик",
	},
	mod_option_flashlight = {
		en = "Flashlight",
		de = "Lichtquelle",
		["zh-cn"] = "战术手电",
		["zh-tw"] = "照明裝置",
		ru = "Фонарик",
	},
	mod_option_flashlight_tooltip = {
		en = "Equips servo friend with a flashlight.",
		de = "Rüstet Servo Freund mit einer Lichtquelle aus.",
		["zh-cn"] = "战术照明设备控制模块",
		["zh-tw"] = "照明裝置控制模組",
		ru = "Вы оснащаете серводруга фонариком.",
	},
	mod_option_flashlight_type = {
		en = "Flashlight Type",
		de = "Lichtquelle Typ",
		["zh-cn"] = "手电筒类型",
		["zh-tw"] = "照明裝置類型",
		ru = "Тип фонарика",
	},
	mod_option_flashlight_type_tooltip = {
		en = "Select the flashlight type.",
		de = "Lichtquelle Typ auswählen.",
		["zh-cn"] = "选择手电筒类型",
		["zh-tw"] = "選擇照明裝置類型",
		ru = "Тут можно выбрать тип фонарика.",
	},
	mod_option_flashlight_type_small = {
		en = "Small",
		de = "Klein",
		["zh-cn"] = "小型",
		["zh-tw"] = "小型",
		ru = "Маленький",
	},
	mod_option_flashlight_type_large = {
		en = "Large",
		de = "Groß",
		["zh-cn"] = "大型",
		["zh-tw"] = "大型",
		ru = "Большой",
	},
	group_flashlight_color = {
		en = "Flashlight Color",
		de = "Lichtquelle Farbe",
		["zh-cn"] = "战术照明光谱配置",
		["zh-tw"] = "照明光譜設定",
	},
	mod_option_flashlight_color_red = {
		en = "Red",
		de = "Rot",
		["zh-cn"] = "赤红频段",
		["zh-tw"] = "紅色頻段",
	},
	mod_option_flashlight_color_red_tooltip = {
		en = "The red component of the flashlight.",
		de = "Rotanteil der Lichtquelle.",
		["zh-cn"] = "调整三原色光波中红色光谱分量强度",
		["zh-tw"] = "調整三原色中紅色光譜的強度",
	},
	mod_option_flashlight_color_green = {
		en = "Green",
		de = "Gruen",
		["zh-cn"] = "翠绿频段", 
		["zh-tw"] = "綠色頻段",
	},
	mod_option_flashlight_color_green_tooltip = {
		en = "The green component of the flashlight.",
		de = "Grünanteil der Lichtquelle.",
		["zh-cn"] = "调节战术手电的绿色波长辐射值",
		["zh-tw"] = "調整照明裝置的綠色波長強度",
	},
	mod_option_flashlight_color_blue = {
		en = "Blue",
		de = "Blau",
		["zh-cn"] = "深蓝频段",
		["zh-tw"] = "藍色頻段",
	},
	mod_option_flashlight_color_blue_tooltip = {
		en = "The blue component of the flashlight.",
		de = "Blaunanteil der Lichtquelle.",
		["zh-cn"] = "设定照明装置的蓝色光子输出功率",
		["zh-tw"] = "設定照明裝置的藍色光強度",
	},
	mod_option_flashlight_always_on = {
		en = "Always On",
		de = "Immer an",
		["zh-cn"] = "持续照明模式",
		["zh-tw"] = "持續照明模式",
		ru = "Включён всегда",
	},
	mod_option_flashlight_only_dark_missions = {
		en = "Only Dark Missions",
		de = "Nur dunkle Missionen",
		["zh-cn"] = "黑暗环境自适应",
		["zh-tw"] = "僅在黑暗環境啟用",
		ru = "Только тёмные миссии",
	},
	mod_option_flashlight_off = {
		en = "Off",
		de = "Aus",
		["zh-cn"] = "关闭照明",
		["zh-tw"] = "關閉照明",
		ru = "Выключен",
	},
	mod_option_flashlight_shadows = {
		en = "Flashlight Shadows",
		de = "Lichtquelle Schatten",
		["zh-cn"] = "动态光影投射",
		["zh-tw"] = "動態陰影效果",
		ru = "Тени от фонарика",
	},
	mod_option_flashlight_shadows_tooltip = {
		en = "Set if flashlight should cast shadows.",
		de = "Legt fest, ob Lichtquelle Schatten werfen soll.",
		["zh-cn"] = "启用手电光源的实时阴影渲染",
		["zh-tw"] = "啟用照明裝置的即時陰影效果",
		ru = "Должен ли свет фонарика отбрасывать тени?",
	},
	mod_option_flashlight_no_hub = {
		en = "Deactivate on Morningstar",
		de = "Deaktivieren auf Morgenstern",
		["zh-cn"] = "在哀星号上禁用",
		["zh-tw"] = "在哀星號上關閉",
		ru = "Выключить в Моунингстар",
	},
	mod_option_flashlight_no_hub_tooltip = {
		en = "Deactivates the flashlight on the Morningstar.",
		de = "Deaktiviert die Lichtquelle auf dem Morgenstern.",
		["zh-cn"] = "在哀星号上禁用伺服颅骨的手电筒功能",
		["zh-tw"] = "在哀星號上關閉伺服器顱骨的照明功能",
		ru = "Фонарик будет выключен в Моунингстар.",
	},

	group_appearance = {
		en = "Appearance",
		de = "Aussehen",
		["zh-cn"] = "外观方案",
		["zh-tw"] = "外觀設定",
		ru = "Внешний вид",
	},
	mod_option_appearance = {
		en = "Appearance",
		de = "Aussehen",
		["zh-cn"] = "外观方案",
		["zh-tw"] = "外觀設定",
		ru = "Внешний вид",
	},
	mod_option_appearance_tooltip = {
		en = "Select the servo friends appearance.",
		de = "Wähle das Aussehen des Servo Freundes.",
		["zh-cn"] = "定制伺服助手的视觉呈现方案",
		["zh-tw"] = "選擇伺服器顱骨的外觀設定",
		ru = "Вы можете выбрать внешний вид вашего серводруга.",
	},
	mod_option_appearance_spineless = {
		en = "Normy",
		de = "Normy",
		["zh-tw"] = "普通型",
	},
	mod_option_appearance_spine = {
		en = "Spiny",
		de = "Spiny",
		["zh-tw"] = "尖刺型",
	},
	mod_option_appearance_decoder = {
		en = "Grabby",
		de = "Grabby",
		["zh-tw"] = "抓取型",
	},
	mod_option_appearance_decoder_2 = {
		en = "Stabby",
		de = "Stabby",
		["zh-tw"] = "刺擊型",
	},

	group_voice = {
		en = "Voice",
		de = "Stimme",
		["zh-cn"] = "语音系统",
		["zh-tw"] = "語音系統",
		ru = "Голос",
	},
	mod_option_use_audio_mod = {
		en = "Use Audio Plugin Mod",
		de = "Audio Plugin Mod benutzen",
		["zh-cn"] = "激活声波增幅协议",
		["zh-tw"] = "啟用聲音增幅模組",
	},
	mod_option_use_audio_mod_tooltip = {
		en = "Use the audio plugin mod to play audio.",
		de = "Benutze die Audio Plugin Mod, um Audio zu spielen.",
		["zh-cn"] = "启用机械教圣音频段解码器播放战术语音",
		["zh-tw"] = "啟用機械教聖音頻段解碼器播放戰術語音",
	},
	mod_option_victory_speech_frequency = {
		en = "Victory Speech Frequency",
		de = "Häufigkeit der Siegesreden",
		["zh-cn"] = "凯旋宣言触发频率",
		["zh-tw"] = "勝利宣言觸發頻率",
	},
	mod_option_victory_speech_frequency_tooltip = {
		en = "Controls how often the servo friend victory speech is played.",
		de = "Legt fest, wie oft die Servo Freund Siegesreden abgespielt werden.",
		["zh-cn"] = "调节机械灵枢播报凯旋圣言的间隔周期（单位：作战分钟）",
		["zh-tw"] = "調整機械靈樞播報勝利宣言的間隔時間（單位：分鐘）",
	},
	mod_option_voice = {
		en = "Voice",
		de = "Stimme",
		["zh-cn"] = "语音系统",
		["zh-tw"] = "語音系統",
		ru = "Голос",
	},
	mod_option_voice_tooltip = {
		en = "The voice the skull friend will be using.",
		de = "Die Stimme, die der Servo Freund verwenden wird.",
		["zh-cn"] = "设置伺服颅骨的战术语音反馈类型",
		["zh-tw"] = "設定伺服器顱骨的戰術語音反饋類型",
		ru = "Голос, который будет использовать серводруг.",
	},
	mod_option_voice_off = {
		en = "Off",
		de = "Aus",
		["zh-cn"] = "静默模式",
		["zh-tw"] = "靜默模式",
		ru = "Выключен",
	},
	mod_option_voice_a = {
		en = "Voice A",
		de = "Stimme A",
		["zh-cn"] = "战术语音A型",
		["zh-tw"] = "戰術語音A型",
		ru = "Голос А",
	},
	mod_option_voice_b = {
		en = "Voice B",
		de = "Stimme B",
		["zh-cn"] = "战术语音B型", 
		["zh-tw"] = "戰術語音B型",
		ru = "Голос Б",
	},
	mod_option_voice_c = {
		en = "Voice C",
		de = "Stimme C",
		["zh-cn"] = "战术语音C型",
		["zh-tw"] = "戰術語音C型",
		ru = "Голос В",
	},

	group_misc = {
		en = "Misc",
		de = "Sonstiges",
		["zh-cn"] = "杂项",
		["zh-tw"] = "雜項",
	},
	mod_option_debug = {
		en = "Debug",
		de = "Debug",
		["zh-cn"] = "调试模式",
		["zh-tw"] = "除錯模式",
	},
	mod_option_debug_tooltip = {
		en = "Enables debug mode.",
		de = "Aktiviert den Debug Modus.",
		["zh-cn"] = "启用调试模式",
		["zh-tw"] = "啟用除錯模式",
	},
	mod_option_avoid_going_into_walls = {
		en = "Wall Detection",
		de = "Wand Erkennung",
		["zh-tw"] = "牆體檢測",
	},
	mod_option_avoid_going_into_walls_tooltip = {
		en = "Prevents the servo friend from going into walls.",
		de = "Verhindert, dass der Servo Freund in Wände geht.",
		["zh-tw"] = "伺服器顱骨會避免穿牆",
	},
	mod_option_avoid_daemonhost = {
		en = "Daemonhost Detection",
		de = "Daemonhost Erkennung",
		["zh-tw"] = "惡魔宿主檢測",
	},
	mod_option_avoid_daemonhost_tooltip = {
		en = "Prevents the servo friend from shining the flashligh on daemonhosts.",
		de = "Verhindert, dass der Servo Freund auf Daemonhosts leuchtet.",
		["zh-tw"] = "伺服器顱骨會避免對惡魔宿主使用手電筒",
	},

	group_aiming = {
		en = "Aiming",
		de = "Zielen",
		["zh-cn"] = "瞄准辅助",
		["zh-tw"] = "瞄準輔助",
		ru = "Прицеливание",
	},
	mod_option_locked_aiming = {
		en = "Locked Aiming",
		de = "Fixiertes Zielen",
		["zh-cn"] = "锁定瞄准姿态",
		["zh-tw"] = "鎖定瞄準姿態",
		ru = "Фиксация на прицеле",
	},
	mod_option_locked_aiming_tooltip = {
		en = "Locks the servo friend into aiming position.",
		de = "Fixiert den Servo Freund in die Zielposition.",
		["zh-cn"] = "将伺服颅骨固定在瞄准姿态，使其光源始终跟随准星方向",
		["zh-tw"] = "將伺服器顱骨固定在瞄準姿態，使其光源始終跟隨準星方向",
		ru = "Серводруг зависает над плечом и светит в направлении вашего прицела.",
	},
	mod_option_aim_sound = {
		en = "Aim Sound",
		de = "Zielsound",
		["zh-cn"] = "瞄准音效反馈",
		["zh-tw"] = "瞄準音效反饋",
		ru = "Звук прицела",
	},
	mod_option_aim_sound_tooltip = {
		en = "Plays a sound when the servo friend is locked into aiming position.",
		de = "Spielt einen Sound, wenn der Servo Freund in die Zielposition fixiert ist.",
		["zh-cn"] = "当伺服颅骨进入锁定瞄准姿态时播放战术提示音",
		["zh-tw"] = "當伺服器顱骨進入鎖定瞄準姿態時播放戰術提示音",
		ru = "Воспроизводит звук, когда серводруг фиксируется в положении прицеливания.",
	},
	mod_option_locked_aiming_priority = {
		en = "Locked Aiming Priority",
		de = "Fixiertes Zielen Priorität",
		["zh-cn"] = "瞄准模式优先权",
		["zh-tw"] = "瞄準模式優先權",
		ru = "Приоритет фиксации на прицеле",
	},
	mod_option_locked_aiming_priority_tooltip = {
		en = "Locked aiming has priority over tagged enemies.",
		de = "Fixiertes Zielen hat Priorität vor markierten Gegnern.",
		["zh-cn"] = "锁定瞄准模式将优先于标记目标追踪功能",
		["zh-tw"] = "鎖定瞄準模式將優先於標記目標追蹤功能",
		ru = "Серводруг будет прилетать к вам и фиксироваться на прицеле даже если уже подсвечивает отмеченных врагов. Иначе останется висеть над врагом.",
	},
	mod_option_hover_particle_effect = {
		en = "Hover Particle Effect",
		de = "Schwebe Partikel Effekt",
		["zh-cn"] = "悬浮粒子特效",
		["zh-tw"] = "懸浮粒子特效",
		ru = "Эффект частиц парения",
	},
	mod_option_hover_particle_effect_tooltip = {
		en = "Enables a particle effect when the servo friend is hovering.",
		de = "Aktiviert einen Partikel Effekt, wenn der Servo Freund schwebt.",
		["zh-cn"] = "启用伺服颅骨悬浮状态下的反重力粒子视觉效果",
		["zh-tw"] = "啟用伺服器顱骨懸浮狀態下的反重力粒子視覺效果",
		ru = "Включает эффект частиц, когда серводруг зависает в воздухе.",
	},
	mod_option_hover_sound_effect = {
		en = "Hover Sound Effect",
		de = "Schwebe Sound Effekt",
		["zh-cn"] = "悬浮音效反馈",
		["zh-tw"] = "懸浮音效反饋",
		ru = "Звуковой эффект парения",
	},
	mod_option_hover_sound_effect_tooltip = {
		en = "Enables a sound effect when the servo friend is hovering.",
		de = "Aktiviert einen Sound Effekt, wenn der Servo Freund schwebt.",
		["zh-cn"] = "激活伺服装置维持悬浮状态时的能量场音频反馈",
		["zh-tw"] = "啟用伺服器顱骨懸浮狀態下的能量場音效",
		ru = "Включает звуковой эффект, когда сервопривод зависает в воздухе.",
	},
}
