
return {
	mod_name = {
		en = "Markers Improved AIO",
		ru = "Улучшенные метки - все в одном",
		["zh-tw"] = "標記改進整合版",
		["zh-cn"] = "图标改进集成",
	},
	mod_description = {
		en = "Combines all my 'Markers' mods in to one easy to install package. ",
		fr = "Combine tous mes mods 'Marqueurs' en un seul paquet facile à installer. ",
		ru = "Markers Improved AIO - Объединяет все мои моды «Меток» в один простой в установке пакет.",
		["zh-tw"] = "將所有「標記」模組整合成一個方便安裝的套件。",
		["zh-cn"] = "集成我的全部‘图标’模组为一个简单的安装包",
	},

	-- AMMO MED MARKERS
	ammo_med_markers_settings = {
		en = "AMMO & MED MARKERS",
		fr = "MARQUEURS DE MUNITIONS ET MÉDICAUX",
		ru = "МЕТКИ - БОЕПРИПАСЫ И МЕДИЦИНА",
		["zh-tw"] = "彈藥與醫療標記",
		["zh-cn"] = "弹药与医疗箱图标",
	},
	ammo_med_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
		["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	ammo_med_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
		["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设置",
	},
	ammo_med_markers_alternate_large_ammo_icon = {
		en = "Use Alternative Icon for Large Ammo pickups",
		fr = "Utiliser une icône alternative pour les grandes munitions ramassées",
		ru = "Использовать альтернативные значки для больших сумок с боеприпасами",
		["zh-tw"] = "使用替代圖示表示大型彈藥",
		["zh-cn"] = "为弹药包（大型）使用替代图标"
	},
	ammo_med_keep_on_screen = {
		en = "Keep on screen",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
		["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	ammo_med_require_line_of_sight = {
		en = "Require line of sight",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
		["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	ammo_med_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
		["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大距离",
	},
	ammo_med_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
		["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	ammo_med_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
		["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	ammo_med_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
		["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},
	display_med_charges = {
		en = "Display Medical Charges",
		fr = "Afficher les charges médicales",
		ru = "Показывать заряды медстанции",
		["zh-tw"] = "顯示醫療充能",
		["zh-cn"] = "显示医疗箱充能",
	},
	display_ammo_charges = {
		en = "Display Ammo Charges",
		fr = "Afficher les charges de munitions",
		ru = "Показывать заряды ящика с боеприпасами",
		["zh-tw"] = "顯示彈藥充能",
		["zh-cn"] = "显示弹药箱充能数",
	},
	display_field_improv_colour = {
		en = "Adjust colour of markers if 'Field Improvisation' talent is active?",
		fr = "Ajuster la couleur pour le talent 'Improvisation sur le terrain' ? ",
		ru = "Изменять цвет маркеров, если активен талант «Полевая импровизация»?",
		["zh-tw"] = "如果啟用「現場應變」天賦，調整標記顏色？",
		["zh-cn"] = "‘临场发挥’天赋激活时，是否调整图标颜色",
	},
	display_field_improv_icon = {
		en = "Display New 'Field Improvisation' talent Icon",
		fr = "Afficher la nouvelle icône du talent 'Improvisation sur le terrain'",
		ru = "Показывать новый значок таланта «Полевая импровизация»",
		["zh-tw"] = "顯示新的「現場應變」天賦圖示",
		["zh-cn"] = "显示新的‘临场发挥’天赋图标",
	},
	display_med_ring = {
		en = "Display Proximity Radius Around Medkits?",
		fr = "Afficher le rayon de proximité autour des kits médicaux ?",
		ru = "Показывать радиус действия медпакетов?",
		["zh-tw"] = "顯示醫療包周圍的接近半徑？",
		["zh-cn"] = "是否显示医疗箱作用范围",
	},
	change_colour_for_ammo_charges = {
		en = "Change ammo crate colour depending on charges left?",
		fr = "Changer la couleur des caisses de munitions en fonction des charges ? ",
		ru = "Изменять цвет значка ящика с боеприпасами в зависимости от оставшихся зарядов?",
		["zh-tw"] = "根據剩餘充能改變彈藥箱顏色？",
		["zh-cn"] = "是否依剩余充能数改变弹药箱图标颜色",
	},
	

	ammo_small_colour = {
		en = "Ammo (Small) Colour",
		fr = "Couleur des munitions (petites)",
		ru = "Цвет малой сумки с боеприпасами",
		["zh-tw"] = "彈藥（小型）顏色",
		["zh-cn"] = "弹药罐（小型）颜色",
	},
	ammo_small_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
		["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	ammo_small_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	ammo_small_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	ammo_small_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	ammo_large_colour = {
		en = "Ammo (Large) Colour",
		fr = "Couleur des munitions (grandes)",
		ru = "Цвет большой сумки с боеприпасами",
        ["zh-tw"] = "彈藥（大型）顏色",
		["zh-cn"] = "弹药包（大型）颜色",
	},
	ammo_large_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	ammo_large_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	ammo_large_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	ammo_large_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "图标颜色",
	},

	ammo_crate_colour = {
		en = "Ammo Crate Colour",
		fr = "Couleur de la caisse de munitions",
		ru = "Цвет ящика с боеприпасами",
        ["zh-tw"] = "彈藥箱顏色",
		["zh-cn"] = "弹药箱颜色",
	},
	ammo_crate_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	ammo_crate_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",	},
	ammo_crate_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	ammo_crate_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	med_crate_colour = {
		en = "Medical Crate Colour",
		fr = "Couleur de la caisse médicale",
		ru = "Цвет медпакета",
        ["zh-tw"] = "醫療箱顏色",
		["zh-cn"] = "医疗箱颜色",
	},
	med_crate_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	med_crate_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	med_crate_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	med_crate_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "图标颜色",
	},

	grenade_colour = {
		en = "Grenade Colour",
		fr = "Couleur des grenades",
		ru = "Цвет гранат",
        ["zh-tw"] = "手榴彈顏色",
		["zh-cn"] = "手雷颜色",
	},
	grenade_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	grenade_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	grenade_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	grenade_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	-- CHEST MARKERS
	chest_markers_settings = {
		en = "CHEST MARKERS",
		fr = "MARQUEURS DE COFFRES",
		ru = "МЕТКИ ЯЩИКОВ",
        ["zh-tw"] = "寶箱標記",
		["zh-cn"] = "宝箱图标",
	},
	chest_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
        ["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	chest_alternative_icon = {
		en = "Use Alternative Icon",
		fr = "Utiliser une icône alternative",
		ru = "Включить альтернативный значок",
        ["zh-tw"] = "使用替代圖示",
		["zh-cn"] = "使用替代图标",
	},
	chest_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
        ["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设置",
	},
	chest_keep_on_screen = {
		en = "Keep on screen",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
        ["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	chest_require_line_of_sight = {
		en = "Require line of sight",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
        ["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	chest_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
        ["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大距离",
	},
	chest_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
        ["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	chest_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
        ["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	chest_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
        ["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},

	chest_icon_colour = {
		en = "Chest Icon Colour",
		fr = "Couleur de l'icône du coffre",
		ru = "Цвет значка ящика",
        ["zh-tw"] = "寶箱圖示顏色",
		["zh-cn"] = "宝箱图标颜色",
	},
	chest_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	chest_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",

	},
	chest_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	chest_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	-- HERETICAL IDOL MARKERS
	heretical_idol_markers_settings = {
		en = "HERETICAL IDOL MARKERS",
		fr = "MARQUEURS D'IDÔLES HÉRÉTIQUES",
		ru = "МЕТКИ ЕРЕТИЧЕСКИХ ИДОЛОВ",
        ["zh-tw"] = "異端雕像標記",
		["zh-cn"] = "异端雕像图标",
	},
	heretical_idol_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
        ["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	heretical_idol_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
        ["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设置",
	},
	heretical_idol_keep_on_screen = {
		en = "Keep on screen",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
        ["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	heretical_idol_require_line_of_sight = {
		en = "Require line of sight",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
        ["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	heretical_idol_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
        ["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大范围",
	},
	heretical_idol_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
        ["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	heretical_idol_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
        ["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	heretical_idol_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
        ["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},

	icon_colour = {
		en = "Icon Colour",
		fr = "Couleur de l'icône",
		ru = "Цвет значка",
        ["zh-tw"] = "圖示顏色",
		["zh-cn"] = "图标颜色",
	},
	icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},

	idol_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

-- MATERIAL MARKERS
	material_markers_settings = {
		en = "MATERIAL MARKERS",
		fr = "MARQUEURS DE MATÉRIAUX",
		ru = "МЕТКИ РЕСУРСОВ",
        ["zh-tw"] = "材料標記",
		["zh-cn"] = "材料图标",
	},
	material_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
        ["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	material_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
        ["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设置",
	},
	material_keep_on_screen = {
		en = "Keep on screen",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
        ["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	material_require_line_of_sight = {
		en = "Require line of sight",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
        ["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	material_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
        ["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大距离",
	},
	material_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
        ["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	material_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
        ["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	material_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
        ["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},
	marker_toggles = {
		en = "Toggle Materials",
		fr = "Basculer les matériaux",
		ru = "Переключение ресурсов",
        ["zh-tw"] = "切換材料",
		["zh-cn"] = "材料切换",
	},
	toggle_large_plasteel = {
		en = "Show Large Plasteel Markers",
		fr = "Afficher les marqueurs des grandes caches de plastacier",
		ru = "Показывать метки больших кусков пластали",
        ["zh-tw"] = "顯示大型塑鋼標記",
		["zh-cn"] = "显示大塑钢储物柜图标",
	},
	toggle_small_plasteel = {
		en = "Show Small Plasteel Markers",
		fr = "Afficher les marqueurs des petites caches de plastacier",
		ru = "Показывать метки малых кусков пластали",
        ["zh-tw"] = "顯示小型塑鋼標記",
		["zh-cn"] = "显示小塑储物柜图标",
	},
	toggle_large_diamantine = {
		en = "Show Large Diamantine Markers",
		fr = "Afficher les marqueurs des grandes caches de diamantine",
		ru = "Показывать метки больших кусков диамантина",
        ["zh-tw"] = "顯示大型金剛晶石標記",
		["zh-cn"] = "显示大金刚砂储物柜图标",
	},
	toggle_small_diamantine = {
		en = "Show Small Diamantine Markers",
		fr = "Afficher les marqueurs des petites caches de diamantine",
		ru = "Показывать малых больших кусков диамантина",
        ["zh-tw"] = "顯示小型金剛晶石標記",
		["zh-cn"] = "显示小金刚砂储物柜图标",
	},
	plasteel_icon_colour = {
		en = "Plasteel Icon Colour",
		fr = "Couleur de l'icône plastacier",
		ru = "Цвет значка пластали",
        ["zh-tw"] = "塑鋼圖示顏色",
		["zh-cn"] = "塑钢图标颜色",
	},
	plasteel_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	plasteel_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	plasteel_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},

	diamantine_icon_colour = {
		en = "Diamantine Icon Colour",
		fr = "Couleur de l'icône diamantine",
		ru = "Цвет значка диамантина",
        ["zh-tw"] = "金剛晶石圖示顏色",
		["zh-cn"] = "金刚砂图标颜色",
	},
	diamantine_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	diamantine_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	diamantine_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	material_small_border_colour = {
		en = "Small Material Cache Border Colour",
		fr = "Couleur de la bordure des petites caches",
		ru = "Цвет границы малого тайника с ресурсами",
        ["zh-tw"] = "小型材料儲存邊框顏色",
		["zh-cn"] = "小材料储存柜颜色",
	},
	material_large_border_colour = {
		en = "Large Material Cache Border Colour",
		fr = "Couleur de la bordure des grandes caches",
		ru = "Цвет границы большого тайника с ресурсами",
        ["zh-tw"] = "大型材料儲存邊框顏色",
		["zh-cn"] = "大材料储存柜颜色",
	},

-- STIMM MARKERS
	stimm_markers_settings = {
		en = "STIMM MARKERS",
		fr = "MARQUEURS STIMM",
		ru = "МЕТКИ СТИМУЛЯТОРОВ",
        ["zh-tw"] = "興奮劑標記",
		["zh-cn"] = "兴奋剂图标",
	},
	stimm_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
        ["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	stimm_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
        ["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设置",
	},
	stimm_keep_on_screen = {
		en = "Keep on screen",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
        ["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	stimm_require_line_of_sight = {
		en = "Require line of sight",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
        ["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	stimm_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
        ["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大距离",
	},
	stimm_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
        ["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	stimm_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
        ["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	stimm_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
        ["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},

	boost_stimm_icon_colour = {
		en = "Boost Stimm Icon Colour",
		fr = "Couleur de l'icône de boost Stimm",
		ru = "Цвет значка стимулятора усиления",
        ["zh-tw"] = "增強興奮劑圖示顏色",
		["zh-cn"] = "专注兴奋剂图标颜色",
	},
	boost_stimm_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	boost_stimm_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	boost_stimm_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	boost_stimm_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	corruption_stimm_icon_colour = {
		en = "Corruption Stimm Icon Colour",
		fr = "Couleur de l'icône de corruption Stimm",
		ru = "Цвет значка стимулятора лечения",
        ["zh-tw"] = "治療針圖示顏色",
		["zh-cn"] = "医疗兴奋剂图标颜色",
	},
	corruption_stimm_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	corruption_stimm_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	corruption_stimm_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	corruption_stimm_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	power_stimm_icon_colour = {
		en = "Power Stimm Icon Colour",
		fr = "Couleur de l'icône de puissance Stimm",
		ru = "Цвет значка стимулятора силы",
        ["zh-tw"] = "戰鬥興奮劑圖示顏色",
		["zh-cn"] = "作战兴奋剂图标颜色",
	},
	power_stimm_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	power_stimm_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	power_stimm_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	power_stimm_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	speed_stimm_icon_colour = {
		en = "Speed Stimm Icon Colour",
		fr = "Couleur de l'icône de vitesse Stimm",
		ru = "Цвет значка стимулятора скорости",
        ["zh-tw"] = "速度興奮劑圖示顏色",
		["zh-cn"] = "敏捷兴奋剂图标颜色",
	},
	speed_stimm_icon_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	speed_stimm_icon_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	speed_stimm_icon_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},
	speed_stimm_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},

	-- TOME MARKERS
	tome_markers_settings = {
		en = "TOME MARKERS",
		fr = "MARQUEURS DE TOME",
		ru = "МЕТКИ КНИГ",
        ["zh-tw"] = "聖典標記",
		["zh-cn"] = "经文图标",
	},
	tome_enable = {
		en = "Enable Markers",
		fr = "Activer les marqueurs",
		ru = "Включить метки",
        ["zh-tw"] = "啟用標記",
		["zh-cn"] = "启用图标",
	},
	tome_general_settings = {
		en = "General Settings",
		fr = "Paramètres généraux",
		ru = "Общие настройки",
        ["zh-tw"] = "一般設定",
		["zh-cn"] = "通用设定",
	},
	tome_keep_on_screen = {
		en = "Keep on screen",
		ru = "Держать на экране",
		fr = "Rester à l'écran",
		ru = "Держать на экране",
        ["zh-tw"] = "保持顯示於螢幕",
		["zh-cn"] = "在画面中持续显示",
	},
	tome_require_line_of_sight = {
		en = "Require line of sight",
		ru = "Требуется прямая видимость",
		fr = "Nécessite une ligne de vue",
		ru = "Должно быть в зоне видимости",
        ["zh-tw"] = "需要視線範圍",
		["zh-cn"] = "需要视野",
	},
	tome_max_distance = {
		en = "Max distance",
		fr = "Distance maximale",
		ru = "Максимальное расстояние",
        ["zh-tw"] = "最遠距離",
		["zh-cn"] = "最大距离",
	},
	tome_max_size = {
		en = "Maximum size of marker",
		fr = "Taille maximale du marqueur",
		ru = "Максимальный размер метки",
        ["zh-tw"] = "標記的最大尺寸",
		["zh-cn"] = "图标最大尺寸",
	},
	tome_min_size = {
		en = "Minimum size of marker",
		fr = "Taille minimale du marqueur",
		ru = "Минимальный размер метки",
        ["zh-tw"] = "標記的最小尺寸",
		["zh-cn"] = "图标最小尺寸",
	},
	tome_alpha = {
		en = "Alpha Multiplier",
		fr = "Multiplicateur d'alpha",
		ru = "Прозрачность",
        ["zh-tw"] = "透明度倍增器",
		["zh-cn"] = "透明度",
	},
	
	grim_colour = {
		en = "Grimoire Colour",
		fr = "Couleur du grimoire",
		ru = "Цвет гримуара",
        ["zh-tw"] = "魔術書顏色",
		["zh-cn"] = "魔法书颜色",
	},
	grim_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	grim_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	grim_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},

	script_colour = {
		en = "Scripture Colour",
		fr = "Couleur des textes sacrés",
		ru = "Цвет писания",
        ["zh-tw"] = "經典顏色",
		["zh-cn"] = "圣经颜色",
	},
	script_colour_R = {
		en = "R",
		fr = "R",
		ru = "К",
        ["zh-tw"] = "紅",
		["zh-cn"] = "红",
	},
	script_colour_G = {
		en = "G",
		fr = "V",
		ru = "З",
        ["zh-tw"] = "綠",
		["zh-cn"] = "绿",
	},
	script_colour_B = {
		en = "B",
		fr = "B",
		ru = "С",
        ["zh-tw"] = "藍",
		["zh-cn"] = "蓝",
	},

	tome_border_colour = {
		en = "Border Colour",
		fr = "Couleur de la bordure",
		ru = "Цвет границы",
        ["zh-tw"] = "邊框顏色",
		["zh-cn"] = "边框颜色",
	},
	
	Gold = {
		en = "Gold",
		fr = "Or",
		ru = "Золото",
        ["zh-tw"] = "金",
		["zh-cn"] = "金",
	},
	Silver = {
		en = "Silver",
		fr = "Argent",
		ru = "Серебро",
        ["zh-tw"] = "銀",
		["zh-cn"] = "银",
	},
	Steel = {
		en = "Steel",
		fr = "Acier",
		ru = "Сталь",
        ["zh-tw"] = "鋼",
		["zh-cn"] = "钢",
	},
}